### PR TITLE
Kohya with A1111

### PR DESCRIPTION
**Pull request by Eugeniusz-Gienek**
## Checklist:

- [ ] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [ ] The description is written in English.
- [ ] The `index.json` and `extension_template.json` have not been modified.
- [ ] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by w-e-w** [comment]
What are you doing?

**Comment by Eugeniusz-Gienek** [comment]
Whoops, my bad

**Comment by Eugeniusz-Gienek** [comment]
Reverted. Wrong repo, sorry.

**Comment by w-e-w** [comment]
this extension is hard to review due to its nature

I haven't actually run the code yet but just by reading the code I have found some alarming things that should be addressed

1. from readme<br>(if You're using python not 3.11 - change accordingly.)<br>sd webui and Kohya's GUI specify the python version 3.10 not 3.11, your explicitly asking people to not follow the instructions we provided even though I believe 3.11 should work but it can still lead to potential unforcing issues, instructing people to do that would cause trouble for use
2. exception files such as the `https://github.com/bmaltais/kohya_ss` you cloned in install should be contained within the extensions directory, do not add files to webui root this could easily lead to issues and will cause trouble if someone were to remove the extensions later on
3. you cannot assume that your extension is installed under `webui_root/extensions/extension_name`, cli flag `--data-dir` can move the location of `extensions dir`
4. you're importing `torch` every time `install.py` is run, importing torch well drastically increase webui load time, you should avoid importing torch unless it is actually necessary <br>this applies to any other lib in install.py as well but torch is particularly heavy, for more detail explanation see PR I made for another extension https://github.com/aria1th/sd-webui-nsfw-filter/pull/2

**Comment by w-e-w** [comment]
it is not because of torch it is because `install.py` is launched by whether you are under a different sub process which means everything you import `install.py` are all new import so the cost is high

---

https://github.com/Eugeniusz-Gienek/kohya-with-automatic1111/blob/1a9fa328a712d0f4a8070d1ab371117fc719f555/install.py#L104-L117
don't create symlinks

two reasons
1. mentioned above you should not put files in web UI root
2. symlinks cannot be created on Windows machine without Administrator privileges unless some settings is changed<br>webui is built for Windows so it should be the standard

I assume that you created those siblings because you think that you need to place those in webui root inorder to make it work
if this is the case then try other the means first
if it still doesn't work you could add stuff to `sys.path` or modify `sys.modules`
https://docs.python.org/3/library/sys.html#sys.path
https://docs.python.org/3/library/sys.html#sys.modules

**Comment by bmaltais** [comment]
Hi, I see work is in progress to integrate the kohya_ss GUI as an extension. I am cool with that. My only request is that there should be no donation link, etc associated to as I as don't personally even monetise the GUI... asnd others should not either.

If there is a change that could be added to the code in my  repo to make the integration easier I will gladly take a PR for it to integrate as long as it does not cause maintenance headhake for future me. The easier we can me training available to users the better.

**Comment by Eugeniusz-Gienek** [comment]
Sure, thanks a lot! I have removed the donation link, no problem. I think I will be able to update the requirements.yml file and will make a pull request in order to be able to support Kohya. Just give me some time, I am setting up a new Gentoo system rn in order ro work with AI - it just takes some time.

**Comment by w-e-w** [comment]
for the record
regarding the funding link (including and other things) was a matter of concern to me as well 
so I try to contact @bmaltais and @kohya-ss about this extention via discord

I only managed to reach kohya
kohya position is
> Regarding Commercial Use: No issues with he making a profit. In fact, my repository is already widely used, and it's likely being utilized for commercial purposes by others too.

note: by my repository kohya is referring to https://github.com/kohya-ss/sd-scripts which is what the Kohya's GUI is based on

I didn't want to relay kohya position untill bmaltais has make his position clear
now bmaltais has now commented on this matter, I belive bmaltais position should be respected

so until future change of status by bmaltais, this extension should not add funding links or it should remove this from this index

note: this is independent from the licensing of the software

**Comment by Eugeniusz-Gienek** [comment]
> for the record
> regarding the funding link (including and other things) was a matter of concern to me as well 
> so I try to contact @bmaltais and @kohya-ss about this extention via discord
> 
> I only managed to reach kohya
> kohya position is
> > Regarding Commercial Use: No issues with he making a profit. In fact, my repository is already widely used, and it's likely being utilized for commercial purposes by others too.
> 
> note: by my repository kohya is referring to https://github.com/kohya-ss/sd-scripts which is what the Kohya's GUI is based on
> 
> I didn't want to relay kohya position untill bmaltais has make his position clear
> now bmaltais has now commented on this matter, I belive bmaltais position should be respected
> 
> so until future change of status by bmaltais, this extension should not add funding links or it should remove this from this index
> 
> note: this is independent from the licensing of the software



Guys, I am really surprised you are that much concerned about someone adding a link to "buymeacoffee" - it's just an ability to make a tip for the efforts, absolutely 100% OPTIONAL and even not pushed into face. Anyways, I have removed it because you asked - no problem.

**Comment by w-e-w** [comment]
no offense
but remember that you're the one who somehow accidentally pushed a funding link to this repository
some sees that was "a malicious attempt of inserting funding link"
the fact that you didn't even try categorizing this your extension doesn't help

normally we don't care if you want to put funding links in readme or github
we only care if you insert things inside the application itself
and is not just the funding link

you are doing lots of unorthodox things as mentioned above https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/259#issuecomment-1890952751

---

there are lots of things that we need to consider when adding an extension of this nature

the following is what I ask kohya

like I said as far as I know it's perfectly legal based on the license
so I'm not asking about legality
I'm asking about are you guys fine if he doing such a thing (from a personal and non-legal perspective)
what I don't want to do is cause "damage" to your project

are you okay with them using your repository to possibly profit
are you okay with the potential possibility of them splitting the community
also the potential trouble of people expecting you to maintain compatibility with a1111
even though you guys have not made such a commitment

people might start opening issues saying that the it don't work
some of the issues might be caused by due to updates of a1111

if you guys have no issues with the possible ramifications that this might bring
then I will continue the procedure of reviewing the extension

**Comment by Eugeniusz-Gienek** [comment]
Screw this. I don't feel that my efforts to make this project better are appreciated. Forget about it. Sorry for bothering. I have closed pull request.

**Comment by w-e-w** [comment]
> Screw this. I don't feel that my efforts to make this project better are appreciated. Forget about it. Sorry for bothering. I have closed pull request.

sorry that you think so

you're still welcome to reopen the PR if you have the change of mind

for the record
I don't personally care if you put your donation link in your github
but others might care
> and when I am reviewing extensions a personal opinions don't really matter
and the index only cares if you put the links in the application itself

my main concern is the compatibility and ramifications this will cause to the boath projects
this is why the donation link issue is not mentioned in https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/259#issuecomment-1890952751
and these are just the compatibility issues that I have already found

the issues I have brought up with Kohya listed in https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/259#issuecomment-1896772386
the summary of reply from Kohya was that it's okay

**Pull request closed without merging**
