### PR TITLE
Add TinyCards entry

### PR DESCRIPTION
**Pull request by SenshiSentou**
## Info 
Super basic extension, but so nice when you have a ton of loras/ checkpoints. Repo: https://github.com/SenshiSentou/sd-webui-tinycards

## Checklist:

- [x] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [x] The description is written in English.
- [x] The `index.json` and `extension_template.json` have not been modified.
- [x] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by w-e-w** [comment]
cool, I like it

---

a small bug report
the card-zoom.svg is not display in crome

| Firefpx | Chrome |
|--------|--------|
| image | image |

**Comment by SenshiSentou** [comment]
> a small bug report the card-zoom.svg is not display in crome

D'ow, thanks for the heads-up; fixed!

**Comment by w-e-w** [comment]
nice
confirm to fix for chrome on my end

**Comment by SenshiSentou** [comment]
> what is "D'ow" ?

It's me misspelling "d'oh" :p As in, the expression Homer Simpson makes when he fucks up

**Comment by w-e-w** [comment]
> > what is "D'ow" ?
> 
> It's me misspelling "d'oh" :p As in, the expression Homer Simpson makes when he fucks up

LOL

**Pull request merged**
