### PR TITLE
Add DemoFusion for WebUI

### PR DESCRIPTION
**Pull request by sebaxakerhtc**
## Info 
Port of DemoFusion as a tab for WebUI
https://github.com/sebaxakerhtc/sd-webui-demofusion

## Checklist:

- [x] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [x] The description is written in English.
- [x] The `index.json` and `extension_template.json` have not been modified.
- [x] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by sebaxakerhtc** [comment]
> in the recent multidiffusion update there is DemoFusion

It works wrong...
I tried to find, why it doesn't work as expected, but can't find the problem. So - I created a tab with original functionality.
You can read about problems of multidiffusion's demofusion [here](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/issues/362#issuecomment-2023378136)

**Comment by w-e-w** [comment]
your extension is currently broken because you model dirs path is wrong
I made a quick fix
- https://github.com/sebaxakerhtc/sd-webui-demofusion/pull/8

---

my thoughts
your extension on missing some crucial things for people to actually use it

one of the main big things is that you're don't have any kind of info text / metadata / saveing of generation parameter of the generated images, this basically means that once you close the web page if you don't remember your seed and all the prompts and all other settings manually then the image will not be able to be recreated

another quality of life qol feature is automatically saving the generated images

**Comment by sebaxakerhtc** [comment]
> you're don't have any kind of info text / metadata / saveing of generation parameter



> my feelings of current state of this extension this is a "Demo"

Hi. And thank you for your help.
I have an issue "Help wanted" because I'm not a developer. I like to use DemoFusion, but don't want to run different instances and it very nice work through the A1111.
Of course I read many guides to understand on how to implement all of this by myself.

**Comment by sebaxakerhtc** [comment]
@w-e-w 
If I understand correctly - now it will use models from A1111 and I can delete Lists of models.
What about LoRA? Will it use LoRAs too?

**Comment by w-e-w** [comment]
ahhh

**Comment by sebaxakerhtc** [comment]
@w-e-w 
Should I revert this PR for now?

**Comment by w-e-w** [comment]
> @w-e-w Should I revert this PR for now?

try this
- https://github.com/sebaxakerhtc/sd-webui-demofusion/pull/9

**Comment by w-e-w** [comment]
@sebaxakerhtc dose this fix work?

**Comment by w-e-w** [comment]
> Btw, can you link me to the info, where I can understand on how to use models chosen in a1111 instead of loading them through my tab?

I think is this file, at least this is the start

https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/b372fb6165c2b0f3990d9a3ff06245d25358c0b8/modules/sd_models.py#L174

**Pull request merged**
