### PR TITLE
Create sd-webui-bilingual-localization-bluelovers.json

### PR DESCRIPTION
**Pull request by bluelovers**
## Info 

Refactored from journey-ad Bilingual translation, rewritten in TypeScript for improved bug fixes and performance enhancements.

## Checklist:

- [x] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [x] The description is written in English.
- [x] The `index.json` and `extension_template.json` have not been modified.
- [x] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by w-e-w** [comment]
I don't use the extension myself so I don't know the details but apparently this extension fixes some issues of the original extension which is no longer being maintained or at least inactive for 10 months

is there any reason to not use the fork as the default?
in other words is there a reason to not replace the original entry?

@journey-ad
> still sending a ping even though I don't think he will respond

**Comment by bluelovers** [comment]
i don't want replace original entry in extensions index

**Comment by w-e-w** [comment]
> i don't want replace original entry in extensions index

if that is the case then you must not use the same repo name `sd-webui-bilingual-localization`
as this would cause your extension to be installed on the same directory as journey-ad version

I'm not sure I'm doing something wrong or not but it doesn't seem to be working for me

I installed a localization for zh_TW
set User interface` - `Localization` as None
and set bilingual Bilingual Localization file to zh_TW
as you an see it;s not working 
the file path the is `undefined` 404
image

---

- change the repo name / URL to somethin else
you can add a prefix or something as long as it is unique

also
- don't input `"added": "2024-06-04",` it is automatically generated on merge

make sure it works or either that or maybe I do something wrong

**Comment by bluelovers** [comment]
> but if that is the case then you must Not use the same repo name sd-webui-bilingual-localization
as this would cause your extension to be installed on the same directory as journey-ad version

> change the repo name

will not change, because want to make user can't install both

> undefined` 404

that bug is from original

**Comment by w-e-w** [comment]
https://github.com/bluelovers/sd-webui-bilingual-localization/commit/a648dfbbef51ae28321487e011f56bc5315d2dc2#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR12

I see that you pushing update that says to fix this issue but are you sure it's fixed?
image
it seems to be so getting the same issue on [a648dfbb](https://github.com/bluelovers/sd-webui-bilingual-localization/commit/a648dfbbef51ae28321487e011f56bc5315d2dc2)

---

> will not change, because want to make user can't install both

you do realize that works both ways right
this basically makes it so that and existing user cannot (hard) switch from journey-ad's version to your version

**Comment by bluelovers** [comment]
image

**Comment by w-e-w** [comment]
如果你英文不好用中文 別玩看圖猜謎
[29b5bf07](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/commit/29b5bf07010a966c6de11c4fde1db98d1dd3972a)
image
image
image

**Comment by bluelovers** [comment]
> 如果你英文不好用中文 別玩看圖猜謎

因為我雖然講中文 但我不論是英文還是中文都跟人有溝通困難XD

看起來只能用傻方法 直接刪除 設定檔內的 bilingual_localization_dirs 讓他在重來一次

**Comment by w-e-w** [comment]
> 看起來只能用傻方法 直接刪除 設定檔內的 bilingual_localization_dirs 讓他在重來一次

可以正常了 算了我不管了 當作通過

**Pull request merged**
