### PR TITLE
Add GeekyRemB extension

### PR DESCRIPTION
**Pull request by GeekyGhost**
## Info 
[]
(https://github.com/GeekyGhost/Automatic1111-Geeky-Remb.git)

## Checklist:

- [x] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [x] The description is written in English.
- [x] The `index.json` and `extension_template.json` have not been modified.
- [x] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by w-e-w** [comment]
I'm guessing you never tested your extension with anything but a square image

**Comment by GeekyGhost** [comment]
Currently porting over from ComfyUI. Video doesn't work on the
automatic1111 port either.

**Comment by GeekyGhost** [comment]
Should be all set, now. Videos working and things have been fully transferred over. Even added a toggle so you can pick which image/video is used for the base height and width since I have a bit of free space play between layers for rotating beyond traditional limits.

**Comment by GeekyGhost** [comment]
> I'm guessing you never tested your extension with anything but a square image

there may have been some confusion, the default is for square images but you use the aspect and scale foreground sliders to adjust when using other aspect ratios. Was this what prevented the approval?

**Comment by w-e-w** [comment]
> this what prevented the approval?

sorry I haven't checked the extension since
~~also the temperature is to hot so I don't want to work~~
 I'll check it now

**Comment by w-e-w** [comment]
- https://github.com/GeekyGhost/Automatic1111-Geeky-Remb/pull/1

**Comment by GeekyGhost** [comment]
I don't really want to make changes or additional updates just yet until I
can properly test them and make sure they still work with my other tools.
So, unless I adjust it to a more established production standards I can't
list it? Fair enough, I'll change the license and etc and leave it as its
own thing. Thank you for your time!

**Comment by w-e-w** [comment]
I'm very confused with your response I'm not entirely sure if you have replied to the wrong message or something

why are you talking about license? you extension is a project license under MIT

> still work with my other tools.

if you want to test my PR go ahead I'm not in a rush

I've said in my last message
> your extension works as is without change
so if you don't agree with my PR then tell me and I will merge as is into the index

just give me a confirmation you do so

but I was suggest you merge my PR before it gets listed index, because and it's current state it doesn't make sense to anyone 
that working with a non-square image

**Comment by GeekyGhost** [comment]
This is probably the most I'm willing to compromise on my own tool lol. Now you can just type in what aspect you want. Decimal, 4:3, 12:4, whatever, you can even just type in landscape or portrait now, you can type in none for the image default, you can type in 0.8, 1.9, whatever now, if it happens to be invalid it defaults to none which is the images default aspect ratio, Does that help you? 

Screenshot 2024-08-18 230825
Screenshot 2024-08-18 230754
Screenshot 2024-08-18 230719
Screenshot 2024-08-18 230931
Screenshot 2024-08-18 230853

**Comment by w-e-w** [comment]
yes it is your own tool and you have to freedom to do anything and you own tool
I do strange thing that only makes sense for me if I'm writing something for my own personal use

that is not the case anymore, you came here and submit your extension to index which means you want your tool to be used by other people, your prospective kind of have to change if I'm making this one not just for you but for others
and more importantly for people that oftentimes don't read documentations

if your tool doesn't make sense to a normal user it's basically meaningless particularly when there is existing alternatives that basically does the same thing
like https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg
> yes I know you add video so you extension haver additional functionality
> but there's also an extension that adds video processing ability for extra tab https://github.com/light-and-ray/sd-webui-video-extras-tab.git
> so the main advantage you have is that your extension is more specialized I guess

my issue (previously) with your extension was it only makes sense for your specific use case and
if anyone wishes to work with non-square images it basically doesn't work or very hard to work with
considering that existing alternative exist I don't really want to put another similar extension that does things in a more convoluted way

---

>  Does that help you

no it doesn't help "me" I probably would never use this extension again after reviewing it
but it helps your extension to be usable by the average user

I'm basically here as a free quality assurance
I'm here to make sure that the extension works
I'm basically a extension reviewer to see if extension even makes sense
if I see something that doesn't make sense problematic or potentially dangerous or I would not merge the extension and sometimes provide potential fixes for the issue
if you're doing something that I don't think that makes sense then I will basically suggest you don't do it
if you think I don't get the use case then you could explain your viewpoint and convince me otherwise

---

since you have read my suggestion even though you didn't write my PR I don't care if you merge my PR as long as it extension works

and I really have no reason to say no to your extension because your extension does something different from existing

---
I made some money in my application to the entry
the extention doesn't fit the description of manipulation
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/blob/1ced95e0fc6fcad332a4adc9bb477ba81524a1d6/tags.json#L13
```diff
{
    "name": "GeekyRemB",
    "url": "https://github.com/GeekyGhost/Automatic1111-Geeky-Remb.git",
    "description": "Advanced Background Removal for Automatic1111 Web UI. Offers multiple AI models, flexible background options, chroma key support, alpha matting, and more for professional-quality image editing.",
-   "added": "2024-08-03",
    "tags": [
        "editing",
-       "manipulations",
        "tab"
    ]
}
```
also in the future don't
also if your future submission to index please don't include the `added` date, that is auto-generated by the workflow on merge

**Comment by GeekyGhost** [comment]
Fair, thank you for your help! I do appreciate your contribution. I'm
autistic, I'm sorry if I come across weird. I tend to over analyze why
people do things. It's been a weird few years man lol. Thank you again.

**Pull request merged**
