### PR TITLE
IF prompt MKR

### PR DESCRIPTION
**Pull request by if-ai**
IF prompt MKR helps to make prompts using a local LLM via Oobabooga API

### CODE REVIEW

**Comment by jtydhr88** [comment]
looks like you changed wrong file, you should change index.json I think

**Comment by w-e-w** [comment]
I'll take care of it

**Comment by if-ai** [comment]
Thank you ❤️

**Comment by w-e-w** [comment]
@if-ai 
you seem to have misunderstood the instructions

form readme
>How to submit extension
If you wish to add an extension to the index, make an entry in extensions directory using extension_template.json, write a short extension description and tag the extension appropriately, then open as a pull request ty!

can you explain to me how you misunderstand it and how I can improve the instructions

note
I also updated the workflow so it won't accidentally run on a fork repository

**Comment by if-ai** [comment]
Thanks, it didn't said which file to use for the instruction in my fork the index file looks like important and I didn't wanted to mess it up😅 the template looked like more fitting to me sorry about that. You could specify which file to edit using the template.

**Comment by w-e-w** [comment]
how do you interpret this
> make an entry in extensions directory using extension_template.json

**Comment by if-ai** [comment]
I think the instructions are clear. It was me I was too tired and didn't follow the instructions correctly. I think I intuitively thought of a main Json file somewhere that I should edit.

**Comment by w-e-w** [comment]
> main Json file somewhere that I should edit
to be fair, that was how it was done until couple days ago

**Comment by if-ai** [comment]
Oh it must have been that then. I think I skimmed through because I had read it a couple of times a few weeks ago. Is a good system I should had read more carefully.

**Pull request merged**
