### PR TITLE
"Bug Infinite" infinite inpainting effect

### PR DESCRIPTION
**Pull request by avantcontra**
An infinite zoom effect tool of Stable Diffusion Webui extension (script), supporting different resolutions and zoom direction.

### CODE REVIEW

**Comment by ClashSAN** [comment]
hi @avantcontra, https://github.com/v8hid/infinite-zoom-automatic1111-webui this is an extension with the outpainting effect, added to the index. 

this is another extension in custom-script format, similar to yours: https://github.com/coolzilj/infinite-zoom

(It's better not to add extensions with duplicate functionality.)

the one from @v8hid (and co) is in tab format, and has upscaling features. not sure of the details, there also seems to be seed resizing. try it and see if it's to your liking.

**Comment by avantcontra** [comment]
Yeah I just found the tab one the day I pulled request mine.
My one I added features like multi-resolution.

Haven't seen the other script one before.

Anyway it's good to have so many open source contributions. PR is not the main target.

**Comment by v8hid** [comment]
@avantcontra You are welcome if you want to contribute on [infinite-zoom-automatic1111-webui](https://github.com/v8hid/infinite-zoom-automatic1111-webui)

**Comment by avantcontra** [comment]
> Some online lists keep track of extensions with similar functionality.
> https://www.sdcompendium.com/doku.php?id=start

@ClashSAN Thanks!

@v8hid 🍻

**Pull request closed without merging**
