### PR TITLE
Nevysha's Cozy Nest

### PR DESCRIPTION
**Pull request by Nevysha**
UI extension with improved UI/UX. Resizable panels, full screen inpainting, and a dark theme. 
https://github.com/Nevysha/a1111-nevysha-comfy-ui.git

### CODE REVIEW

**Comment by w-e-w** [comment]
did a quick test and found that I can not scroll down the page, I was not able access most of the generation parameters

so unless I'm doing something horribly wrong, I don't think this extension is usable at this state

tested on
1920x1080 chrome

**Comment by Nevysha** [comment]
Yes it's probably related to the recent auto1111 update... I'll update this PR after working on a compatibility fix. 

Thanks for your test.

**Comment by ClashSAN** [comment]
@Nevysha hey, are you aware of this project? https://github.com/comfyanonymous/ComfyUI
users will be confused by the name, eg:

"are you aware of the comfy ui extension for webui?"

**Comment by w-e-w** [comment]
image
it's not too late to rename it
iirc GitHub will redirect old request to a reanmed repo

**Comment by ClashSAN** [comment]
@w-e-w lol, just bringing it up, in case they're unaware :)
this happens regularly such as what happened with the name "vicuna" for llm models.
it's up to @Nevysha

**Comment by Nevysha** [comment]
>it's not too late to rename it
iirc GitHub will redirect old request to a reanmed repo
>
>like all I have mentioned the name is really confusing
I was also confused
but since it didn't work when I tested so I didn't mention it

Yes I was afraid that renaming the repo would break everything but turns out github is really smooth. I'm curently working on renaming it : https://github.com/Nevysha/Cozy-Nest

Maybe we can close this PR and I'll make a new one when everything is set up.

**Comment by w-e-w** [comment]
the PR can be edited easily

also see this for redirect to happen in action
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/24

**Comment by w-e-w** [comment]
I saw you update the repo name
and it seems that the extension is working, is it working?
is it okay to merge?

off topic
to be fare, your name is not the worst
that trophy belongs to
```json
"name": "Catppuccin Theme",
"url": "https://github.com/catppuccin/stable-diffusion-webui.git",
```
https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/5813#discussioncomment-5113075
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7539#issue-1571127595

**Comment by Nevysha** [comment]
Haha you are right.

I updated the PR to rename this extension along with the new repo URL. And yes it's working. Feel free to merge !

**Pull request merged**
