### PR TITLE
add translation and speech to text extension

### PR DESCRIPTION
**Pull request by athos54**
## Checklist:

- [x] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [x] The description is written in English.
- [x] The `index.json` and `extension_template.json` have not been modified.
- [x] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by athos54** [comment]
hi @w-e-w I have updated the pr, check it when you can

**Comment by athos54** [comment]
ok, thanks, I'll check it

**Comment by w-e-w** [comment]
I am sitting this PR as a draft for now, reopened it this when there's more updates

**Comment by w-e-w** [comment]
closing this PR for now
feel free to reopen if there's any updates

**Pull request closed without merging**
