### PR TITLE
add latent consistency models extension

### PR DESCRIPTION
**Pull request by 0xbitches**
## Info 

Extension URL:
https://github.com/0xbitches/sd-webui-lcm

More about Latent Consistency Models:
https://latent-consistency-models.github.io/

## Checklist:

- [x] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [x] The description is written in English.
- [x] The `index.json` and `extension_template.json` have not been modified.
- [x] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by w-e-w** [comment]
webui does not come with the diffusers by default, you need to install it by creating a `install.py`

```shell
*** Error loading script: main.py
    Traceback (most recent call last):
      File "B:\GitHub\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "B:\GitHub\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "B:\GitHub\stable-diffusion-webui\extensions\sd-webui-lcm\scripts\main.py", line 4, in <module>
        from lcm.lcm_scheduler import LCMScheduler
      File "B:\GitHub\stable-diffusion-webui\extensions\sd-webui-lcm\lcm\lcm_scheduler.py", line 25, in <module>
        from diffusers import ConfigMixin, SchedulerMixin
    ModuleNotFoundError: No module named 'diffusers'
```

something like https://github.com/w-e-w/sd-webui-nudenet-nsfw-censor/blob/main/install.py
this is for onnxruntime but the same for diffusers

**Comment by w-e-w** [comment]
I after installing diffusers and are getting this error
```shell
*** Error loading script: main.py
    Traceback (most recent call last):
      File "B:\GitHub\stable-diffusion-webui\modules\scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "B:\GitHub\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "B:\GitHub\stable-diffusion-webui\extensions\sd-webui-lcm\scripts\main.py", line 72, in <module>
        pipe = LatentConsistencyModelPipeline.from_pretrained(
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1105, in from_pretrained
        loaded_sub_model = load_sub_model(
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 472, in load_sub_model
        loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1825, in from_pretrained
        return cls._from_pretrained(
      File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 2044, in _from_pretrained
        raise ValueError(
    ValueError: Non-consecutive added token '<|startoftext|>' found. Should have index 49408 but has index 49406 in saved vocabulary.
```

**Comment by 0xbitches** [comment]
@w-e-w Yes, that is unfortunately due to LCM's model card containing an extra `add_tokens.json`. I detailed a solution in the README of the extension: https://github.com/0xbitches/sd-webui-lcm#known-issues

**Comment by 0xbitches** [comment]
I have also created `install.py` with diffusers.

**Comment by w-e-w** [comment]
> @w-e-w Yes, that is unfortunately due to LCM's model card containing an extra `add_tokens.json`. I detailed a solution in the README of the extension: https://github.com/0xbitches/sd-webui-lcm#known-issues

ok, apparently I'm blind

tested and working, and wow that's fast

**Pull request merged**
