### PR TITLE
Create sd-webui-depth-lib.json

### PR DESCRIPTION
**Pull request by w-e-w**
## Info 
@jexom I just notice your extension and would like to add it to the index, if you have any issues with the description tagging Etc please respond

schedule to be added in a week if no reply
```json
{
    "name": "Extension_Name",
    "url": "https://github.com/jexom/sd-webui-depth-lib.git",
    "description": "Depth map library for use with the Control Net extension",
    "tags": [
        "tab"
    ]
}
```

## Checklist:
- [x] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [x] The description is written in English.
- [x] The `index.json` and `extension_template.json` have not been modified.
- [x] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by alexbofa** [comment]
Hello, this extension doesn't work stable. After installed, when you start again Stable Diffusion. Has error 
image
image

It's after updates Gradio, about May 2023

**Comment by w-e-w** [comment]
hum odd why didn't this happen when I did my initial test of this extension last week
I guess I better remove this extension for now as I have to potential to break web UI

**Comment by w-e-w** [comment]
ah I see
I must have been testing with the dev branch
and we must have changed something so that the error doesn't happen
I revert this one now and add this back in once death is push to master

**Comment by jtydhr88** [comment]
I provided a fix for who want to use this extension but facing KeyError: 'dataset' issue, see https://github.com/jexom/sd-webui-depth-lib/issues/36

**Pull request merged**
