### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by gurralol**
## Checklist:

- [x] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [x] The description is written in English.
- [x] The `index.json` and `extension_template.json` have not been modified.
- [x] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by gurralol** [comment]
Any feedback on how I could improve the extension is greatly appreciated!

**Comment by w-e-w** [comment]
> Any feedback on how I could improve the extension is greatly appreciated!

Are you seriously asking this question?
have you heard of img2img, it's kind of a big thing you know

---

also what sets your extension apart from the existing ones
what does your extension do better
image

**Comment by gurralol** [comment]
> > Any feedback on how I could improve the extension is greatly appreciated!
> 
> Are you seriously asking this question? have you heard of img2img, it's kind of a big thing you know
> 
> also what sets your extension apart from the existing ones what does your extension do better image

You don't need to be so hurtful.
I installed the extensions in your image. The one that has similar functionality is the "Aspect Ratio Resolutions selector-xhox" extension, but I don't like the style of it, the buttons are too big and they're not organized well. I'll consider adding my extension to the img2img tab and adding aspect-ratio text to the resolutions. Thanks for the feedback!

**Comment by w-e-w** [comment]
yes very true I do not need to uses sarcasm

but you do realize that when you ask for feedback for your extension, you are asking someone to spend the time to conduct a full code review of your extension and then execute your extension on their machine

if your extension is unfinished then this is just wasting people's time

> your extension is objectively unfinished as  you have added it to both txt2img and img2img but it only works on txt2img

the truth is I have already reviewed the extension two days ago about 30 minutes after you submitted your pull request

I did not say anything because for me the extension is obviously unfinished, I have trusted you will fix the extension by I have the time do a full review
but two days later you decide to add for feedback with no change to the code
to get feedback

if you ask feedback, it implies that you think that your extension is finished and is asking for anything that can be improved 

but your extension even isn't finished
this is extremely annoying

**Comment by w-e-w** [comment]
generally we encouraged people to contribute to existing extensions as opposed to creating new similar ones, this reduces clutter to the index, and more importantly this keeps old extensions maintained

so for your extension to be listed on the index it needs to achieve following

- it needs to be at least equal or surpass existing similar extensions
- the use case is drastically different

**Comment by gurralol** [comment]
Ok, I understand. I apologize for posting a redundant extension. I'm new to programming and github and just wanted to contribute but I understand the points you're making about time spent reviewing and cluttering the index. I'll keep it in mind for my next work! Thank you for the feedback.

**Comment by w-e-w** [comment]
no you don't get the point
I'm okay with similer extensions
everyone has their own take on how they like things done like you want different styles and different sorting orders this is good
if you do something good enough then it's not redundant anymore

the only real issue I have with your extention and why I replied in that manner is that you submitted a obviously incomplete unfinished extension

it is totally fine at extension has bugs, most new extension authors
makes basic mistakes here and there that's totally fine I'm willing to help and often give advice if not make straight out pull request to fix those issues
> if you want proof of this you can see they possibly hundreds of PRs that have made in the past

but it is not the case with your extension
making the issue more aggravating is that your extension is not that complex your extension is obviously an objectively unfinished
is like you only written 1/2 of a book with a table of contents that indicates that it is 1/2 of a half of the book
but you decide to submit it to be reviewed and published
if you had written some description hear in this PR about how your extension is unfinished, what state of development is the extension, you're looking for what sort of feed, and what you hope whoever is reading this PR will do
then my reaction will be very different

but since you left no explanation, it's basically saying that this is a fully developed extension ready to be used by the masses
but as we've known this is not the case
and yet just after 2 days you decide to ask for "feedback" as if there isn't anything obviously wrong with your extension

making it more aggravating is that your extension is not complex
this makes me explode

---

now as mentioned previously I would prefer that you contribute to existing extensions
but you would notice that I haven't closed this pull request

if you think that your extension is going a different direction then existing extensions
and wish to submit your extension to the public here

go ahead continue development, make it actually complete, list out the reasons, list out what your exception do different from existing similar extension
and I will most likely add it to index

just don't submit extensions that are obviously incomplete, that is just wasting people's time

---

the keeping here is that you're not writing an extension for yourself you're writing for the public

everyone can write their own extensions / code and they might have reasons to do it in ways that doesn't even make sense
> I've written lots of code in past that are meant to be used by me personally
for example a command line operations with half of its arguments hard coded with no documentation
it makes perfect sense for me to written like that because I never intend this code to be used by anyone else but me it's easier for me to just change the code and change the behavior as opposed to writing a proper command line interface

but the prospective needs to change when you're writing something for the public

**Comment by gurralol** [comment]
"the only real issue I have with your extention and why I replied in that manner is that you submitted a obviously incomplete unfinished extension"

You communicate your main frustration clearly: "you submitted a obviously incomplete unfinished extension".

My extension has since the point of upload & pull request worked in accordance with how it is described to work on its github page (the URL of which in the .json file): "Automatic1111 extension for quick input of SDXL resolutions in the txt2img tab."

I will try to add it to the img2img tab, but it might take some time because I don't know how to yet.
If this is a problem, reject the pull request.

Thank you again for the feedback.

**Comment by w-e-w** [comment]
yes that is true
> Automatic1111 extension for quick input of SDXL resolutions in the txt2img tab

but you realize you literally have your extension showed on both tabs right
so it's basically a case of "your words does not match your actions" "code does not match description"
when this happens code takes precedence, because it's actually the thing

> I will try to add it to the img2img tab, but it might take some time because I don't know how to yet.

how don't you know how to do it? don't you know how your code works it's trivia?
you already implemented txt2img tab, but you hard coded the element id in to the javascript and so it always targets the txt2img tab

to make the code works on boath txt2img img2img tabs you

either use two functions hardcoded hard coded and depending on it the UI is img2img use
the appropriate function
or create a function with an extra argment that takes the element id so thatthe functon knows what element to target

**Comment by gurralol** [comment]
Ooh, I didn't realize it also showed in the img2img tab. That's my mistake, I apologize. I'll update the description.

I don't know how to do some of these things because I'm very new to programming. This is my first project ever uploaded.

I'll see if I can fix the code. Thanks for the feedback.

**Comment by w-e-w** [comment]
so I've asked other Developers think on how I handle
the contraction with you and some thinks
> I think I agree with ~~redacted~~. not to push the nail too deep, but to me it just seem a bit too harsh, especially for a first contributor
I think they just really don't know things you might have been accustomed to for a long time and seem obvious 

so my apologies for exploding on you, I could have to deliver the message in a nice manner
but I will still remain on my judgment on extension saying that it is unfinished

---

unrelated
one of the other developers recommend a fork of existing extension that also dose resolution aspect ratio selector
- https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/330

**Comment by gurralol** [comment]
No worries! I appreciate the apology. Your perspective about the state of my extension is valuable to me. I'm learning so much about programming and this website still. I apologize for opening a pull request without first getting feedback on my code in other places. I wont do the same mistake again.

I'll study the fork you linked and try to learn from it! 🔍

**Pull request closed without merging**
