### PR TITLE
Add mov2mov extension

### PR DESCRIPTION
**Pull request by DavG25**
This extension is a [fork](https://github.com/DavG25/sd-webui-mov2mov) of the original [mov2mov](https://github.com/Scholar01/sd-webui-mov2mov), it processes videos frame-by-frame to create a video using Stable Diffusion

<br>

Compared to the original, this fork differs in a few ways:
- It no longer uses the OpenH264 library (imageio is used instead), so users don't have to download the libopenh264 binary and put it in the system files
- UI and scripts are changed to support the latest version of https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81 while also supporting older versions (such as https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a9eab236d7e8afa4d6205127904a385b2c43bb24)
- Translated to English
- The necessary models used in MODNet are downloaded automatically

Full changes compared to the origin repo can be seen [here](https://github.com/Scholar01/sd-webui-mov2mov/compare/master...DavG25:sd-webui-mov2mov:master)

### CODE REVIEW

**Comment by w-e-w** [comment]
since the upstream repo seems to be actively maintained, I think I need to ask these questions
@Scholar01 
are you aware of this fork? do you have plans of merging the changes to your upstream repo?
do you prefer this fork get added to the index or your upstream repo gets added?
or you have plans to add your repo to the index?
(note if this is the case then it's best to have a english readme)

@DavG25 
are you in communication with Scholar01

**Comment by DavG25** [comment]
> @DavG25
> are you in communication with Scholar01

I'm not currently in communication with Scholar01, but it seems best to wait for the answers to the questions you mentioned, since they may have plans to eventually add the extension to this list or merge new changes

**Comment by Scholar01** [comment]
I’m sorry, I only saw this message after I submitted my repository to the index. My current plan is to add my repository to the index, and I’ll add the English README file later.

**Comment by Scholar01** [comment]
@DavG25 Hello, I’m truly sorry. I’ve been very busy recently, which led to some outstanding issues. I’ve also noticed and referred to your fork. If you’re interested, we can maintain it together.

**Comment by DavG25** [comment]
> @DavG25 Hello, I’m truly sorry. I’ve been very busy recently, which led to some outstanding issues.

No problem at all, I'm glad to hear you're back

<br>

> I’ve also noticed and referred to your fork. If you’re interested, we can maintain it together.

Sure, I would be happy to maintain it together, and if there's anything you want to merge from my fork into the main repository feel free to do it

<br>

I'm closing this PR in favor of https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/194

**Comment by w-e-w** [comment]
for the record, I feel bad letting this sit for almost 5 months
I should have offered you the opinion to rename your fork and add it to the index

**Pull request closed without merging**
