### PR TITLE
add faceswaplab

### PR DESCRIPTION
**Pull request by glucauze**
## Info 

https://github.com/glucauze/sd-webui-faceswaplab :  Extended faceswap with multiple faceswaps, inpainting, checkpoints, .... 

doc here https://glucauze.github.io/sd-webui-faceswaplab/

## Checklist:
- [ ] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [X] The description is written in English.
- [X] The `index.json` and `extension_template.json` have not been modified.
- [X] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by w-e-w** [comment]
image
if you didn't do anything these are clickable
- [x] 123
- [ ] 456
```
- [x] 123
- [ ] 456
```
or you want to put `x` in manually then put it properly

**Comment by w-e-w** [comment]
I made some changes
don't like the idea of having a URL in the description
what do you prefer your extension to be named `FaceSwapLab` `FaceSwap Lab` `sd-webui-faceswaplab`?

**Comment by glucauze** [comment]
Oh thx, we can keep sd-webui-faceswaplab or whatever name has been choosen :)

**Comment by w-e-w** [comment]
done

**Comment by glucauze** [comment]
thx :)

**Pull request merged**
