### PR TITLE
Add stable-diffusion-webui-auxilary-api

### PR DESCRIPTION
**Pull request by aria1th**
## Info 
https://github.com/aria1th/webui-model-uploader
Attaches additional API routes, such as model upload / delete / sync
upload and delete API is functional, most of them.

## Checklist:

- [x] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [x] The description is written in English.
- [x] The `index.json` and `extension_template.json` have not been modified.
- [x] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by aria1th** [comment]
Thank you for the review!
I also noticed that authentication is not automatically applied to FastAPI APP unless it uses 'depends' argument, so it is now insecure state.

So the plan is:

1. Implement basic auth for everything first. API auth should be applied at default.
2. Implement CLI args for supporting different credentials simply.
3. Some more proper documents : (actually FastAPI offers docs for endpoints, but one that in repository is better).

**Comment by w-e-w** [comment]
I'll set this PR as a draft for now, reopened and maybe ping me when it's ready

also in the futuredon't `added_date`
it will be automatically generated by github action when merged into the index

**Comment by aria1th** [comment]
@w-e-w Finished implementing Basic Auth for all endpoints! (also offers some fancy wrapper that replaces app.post in-place)

https://github.com/aria1th/webui-model-uploader/commit/ed1a970f5ea162a321e0b8de6db1bf06d737de71

**Comment by w-e-w** [comment]
damn I thought it would take you a couple days at least
I was going to bed but it's your fault that I'm not in bed right now
I had a quick look and did a simple test looks to be working

**Comment by w-e-w** [comment]
wait a moment is your script online?

**Comment by aria1th** [comment]
@w-e-w What do you mean by `online`?

**Comment by aria1th** [comment]
No, I thought it was for some network-accessing (optionally, maybe local too) extensions xd

**Comment by w-e-w** [comment]
you do have "model downloader"
which does require connecting to server service
typically model downloaders are classified as online as it relies on external services
but we do make acceptance for one time asset downloads

I think the use case is a bit different from the normal model civitai downloader
it's more similar to a one-time asset download tool
so I think I can classify this as not requiring the online tag

**Comment by w-e-w** [comment]
online tag removed and merged

**Pull request merged**
