### PR TITLE
add community index

### PR DESCRIPTION
**Pull request by todhm**

### CODE REVIEW

**Comment by w-e-w** [comment]
tag `online` 
describe clearly what it does

what server this using who run the server 
`newtypev3-server-vjiloyvjvq-an.a.run.app`

TOS etc? let people know what are they getting by installing / using this extension

**Comment by todhm** [comment]
Dear w-e-w
we deployed an online community extension that helps users to view other users' prompts. 
By downloading this extension you can see other users' images with search filters. 
User who is agreed to share their image upload their prompt & configurations to our server through 
`newtypev3-server-vjiloyvjvq-an.a.run.app` API (only when they check share image checkbox)

**Comment by ORANZINO** [comment]
> tag `online` describe clearly what it does
> 
> what server this using who run the server `newtypev3-server-vjiloyvjvq-an.a.run.app`
> 
> TOS etc? let people know what are they getting by installing / using this extension

Dear w-e-w
we deployed an online community extension that helps users to view other users' prompts.
By downloading this extension you can see other users' images with search filters.
User who is agreed to share their image upload their prompt & configurations to our server through
`newtypev3-server-vjiloyvjvq-an.a.run.app` API (only when they check share image checkbox)

**Comment by todhm** [comment]
> tag `online` describe clearly what it does
> 
> what server this using who run the server `newtypev3-server-vjiloyvjvq-an.a.run.app`
> 
> TOS etc? let people know what are they getting by installing / using this extension

Dear w-e-w
I've updated the index with an online tag and description like you mentioned. 
We deployed an online community extension that helps users to view other users' prompts. 
By downloading this extension you can see other users' images with search filters. 
User who is agreed to share their image upload their prompt & configurations to our server through 
`newtypev3-server-vjiloyvjvq-an.a.run.app` API (only when they check share image checkbox)

**Comment by w-e-w** [comment]
After some discussion lots of us from the dev server feel uneasy about your extension
mainly due to lack of transparency further and intent

As such I (no represents other) will not be adding this to the index

I will set the PR to a Draft for now
depending on further info / future development of the extension this may get added in the future

also why setup a new services instead of integrating a existing one?

**Comment by w-e-w** [comment]
the repo has been removed from the org

**Comment by todhm** [comment]
Hello!
The reason why Feed extension is necessary for Web UI is as follows.

I have been using Web UI since January. In Korea, there is a community called “Arca.live” where AI images are actively shared. I discovered a unique user loop:

1. Browse AI images in the community.
2. Find AI images you want to recreate in the community.
3. Create your own image by referring to the parameters of the image you want to recreate in Web UI.
4. Show off well-made images in the community.

I believe that the value of AI images lies in browsing, recreating, and showing off.
To access this community directly within Web UI, I developed a Feed extension, which requires using an external server to save images.

Web UI is a creation tool, but if community features are added, it would be a great help in building the user loop or ecosystem I mentioned earlier. Image producers can gain reputation and potentially generate revenue, while image consumers can easily browse images and use them as inputs for the Web UI tool.

Can you please let me know if there are any concerns?

PS. And also I changed the github address. I will make a new pull request with this repo 'github.com/todhm/sd_feed'.
plz approve it! :)

**Comment by CapsAdmin** [comment]
> Hello! The reason why Feed extension is necessary for Web UI is as follows.
> 
> I have been using Web UI since January. In Korea, there is a community called “Arca.live” where AI images are actively shared. I discovered a unique user loop:
> 
>     1. Browse AI images in the community.
> 
>     2. Find AI images you want to recreate in the community.
> 
>     3. Create your own image by referring to the parameters of the image you want to recreate in Web UI.
> 
>     4. Show off well-made images in the community.
> 
> 
> I believe that the value of AI images lies in browsing, recreating, and showing off. To access this community directly within Web UI, I developed a Feed extension, which requires using an external server to save images.
> 
> Web UI is a creation tool, but if community features are added, it would be a great help in building the user loop or ecosystem I mentioned earlier. Image producers can gain reputation and potentially generate revenue, while image consumers can easily browse images and use them as inputs for the Web UI tool.
> 
> Can you please let me know if there are any concerns?
> 
> PS. And also I changed the github address. I will make a new pull request with this repo 'github.com/todhm/sd_feed'. plz approve it! :)

Maybe if A1111 adds the ability to load data via urls, websites or browser extensions can make use of that. It may even be possible to examine png images on certain websites and extract the metadata from them.

**Pull request closed without merging**
