### PR TITLE
Add Characteristic_Guidance_Web_UI.json

### PR DESCRIPTION
**Pull request by scraed**
Characteristic_Guidance_Web_UI

New guidance method providing large CFG scale correction for classifier-free guidance. Compatible with existing sampling methods.

## Checklist:

- [x] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [x] The description is written in English.
- [x] The `index.json` and `extension_template.json` have not been modified.
- [x] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by w-e-w** [comment]
hi sorry took awhile for me to start merging extension to index

I have tested your extension and it does work so it can be added
but there are some issues that I will prefer that you sorted out before it gets merged I've sent over a PR with explanations
https://github.com/scraed/CharacteristicGuidanceWebUI/pull/1

**Comment by w-e-w** [comment]
I remove `tab` `extras` tag and added `science`
seems more fitting
see https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/blob/extensions/tags.json

**Comment by w-e-w** [comment]
nice I see you have made some changes the keys names used

are the key names final
I want to confirm because it's better that you finalize them before I merge this into index

**Comment by scraed** [comment]
@w-e-w Yes, I have merged the PR to fix the infotext issue with some name changes. I think they are final. Thanks again for your PR!

**Comment by w-e-w** [comment]
great

**Pull request merged**
