### PR TITLE
Add stable-diffusion-database-manager

### PR DESCRIPTION
**Pull request by nicholas-ooi**
## Checklist:

- [x] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [x] The description is written in English.
- [x] The `index.json` and `extension_template.json` have not been modified.
- [x] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by w-e-w** [comment]
continue of https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/260#issuecomment-1890396505

> The general idea is for advance users who might want to generate images spread across multiple database systems or their existing databases.

I assume that is the case

there was a part of my comment that I deleted from my last message
> which makes this extension easier to use for novice users
> then again a novice user probably don't know what it database is so they won't be using this extension in the first place

but even this is targeted towards advanced users who knows their ways around databases, I think it's still good to have SQLlite as a backend, as this allows the user to test the extension to see if it suits their workflow before having to go through the trouble of setting up a database,
and as I mentioned above depending on the users workflow, if they're not working for distributed system SQLlite mught be good enough, anything more than that might be overkill for them

note this is just a suggestion, I'm not forcing you to do anything

---

haven't run your code yet but already found some issues 
already found some issues

https://github.com/nicholas-ooi/stable-diffusion-database-manager/blob/0fcb597fdb962b2d54c14755e678322fdb4d21e0/scripts/database_manager.py#L45

that's going to break, when when the extension is not installed under the default name or if `--data-dir` is used

as the extention root is added tp sys.path you should import it as `scripts.databases` 
also the name `databases` is rather generic, if someone other extension uses the same name it will cause name collision

---

you also seem to be only grabbing basic information from `processed` and not the full information
https://github.com/nicholas-ooi/stable-diffusion-database-manager/blob/0fcb597fdb962b2d54c14755e678322fdb4d21e0/scripts/databases/mysql_database.py#L108-L119
you are also missing parameters such as subseed (variation seed) seed resize from also `extra generation parameters` used by extinctions
is there any reason why you don't include other information

**Comment by w-e-w** [comment]
also if you wish to store information on each image and not just the entire job
the `infotexts` (list of string that corresponding to each image returned the the results gallery) should contain all the parameters a image
to extract information from `infotext` (str) it needs to be parsed by [`parse_generation_parameters()`](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/cf2772fab0af5573da775e7437e6acdca424f26e/modules/generation_parameters_copypaste.py#L211)

**Comment by nicholas-ooi** [comment]
Thanks! That is a really good suggestions. Appreciate the review in great details.
Probably would revise it in future version releases

Yep the naming collision is sure an issue.

**Comment by w-e-w** [comment]
first off I have little experience with databases

can you verify it again that your extension is working with your test database
or am I doing something stupid due to of my lack of knowledge on databases

---

I spinned up you test databases that you provided for a quick test with `PostgreSQL`

but I encountered errors

my config
image

and I got an error like this

```
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:02<00:00, 11.28it/s]
ERROR:extensions.stable-diffusion-database-manager.scripts.databases.postgres_database:Error inserting data: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(255):01<00:00, 13.86it/s]

[SQL: INSERT INTO t (m, i) VALUES (%(m)s, %(i)s) RETURNING t.id]
[parameters: {'m': '{"seed": 3447407284, "prompt": "Closeup of brown hair woman knightin shiny metal armor, detailed skin, wearing jewellery, masterpiece, in front of a  ... (74 characters truncated) ...  bad art",
"steps": 25, "sampler": "Euler a", "cfg_scale": 5.5, "size": [420, 640], "model_hash": "620138fee8", "model": "darkSushi25D25D_v10"}', 'i': <psycopg2.extensions.Binary object at 0x000001B781445020>}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
Error after post processing: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(255)

[SQL: INSERT INTO t (m, i) VALUES (%(m)s, %(i)s) RETURNING t.id]
[parameters: {'m': '{"seed": 3447407284, "prompt": "Closeup of brown hair woman knightin shiny metal armor, detailed skin, wearing jewellery, masterpiece, in front of a  ... (74 characters truncated) ...  bad art",
"steps": 25, "sampler": "Euler a", "cfg_scale": 5.5, "size": [420, 640], "model_hash": "620138fee8", "model": "darkSushi25D25D_v10"}', 'i': <psycopg2.extensions.Binary object at 0x000001B781445020>}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
Total progress: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:02<00:00, 11.62it/s]
Total progress: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:02<00:00, 13.86it/s]

```

I did not create a table myself I just use your built in auto create table if not exist
you seem to have set the metadata string column to be only 255 long which I easily exceeded with a pretty standard image
I adjusted your code and create a table metadata that is much longer and try again

this time I I got different error

```
RROR:extensions.stable-diffusion-database-manager.scripts.databases.postgres_database:Error obtaining the table: (psycopg2.errors.SyntaxError) syntax error at or near "4294967295"█████████| 25/25 [00:19<00:00, 13.82it/s]
LINE 4:  m2 VARCHAR(4294967295),
                    ^

[SQL:
CREATE TABLE t1 (
        id SERIAL NOT NULL,
        m2 VARCHAR(4294967295),
        i3 BYTEA,
        PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/20/f405)
Error after post processing: (psycopg2.errors.SyntaxError) syntax error at or near "4294967295"
LINE 4:  m2 VARCHAR(4294967295),
                    ^

[SQL:
CREATE TABLE t1 (
        id SERIAL NOT NULL,
        m2 VARCHAR(4294967295),
        i3 BYTEA,
        PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/20/f405)

```
I didn't bother investigating what this means and how to resolve it

**Comment by w-e-w** [comment]
@nicholas-ooi 
knock knock anyone home

**Comment by nicholas-ooi** [comment]
hey, thanks for sharing all the issues, will look into it during my free time, probably weekends, been swarmed by work 🤪

**Comment by w-e-w** [comment]
no problem take your time
just don't want the message get buried

**Comment by nicholas-ooi** [comment]
hey @w-e-w have updated https://github.com/nicholas-ooi/stable-diffusion-database-manager

You can try it again, have look into all the issues you've mentioned, hope it should be good.

Added SQlite support as well, not sure if there are other issues! did some user testing with very lengthy details, seems ok so far.

Probably will refactor for better code of separation in future releases..

**Comment by w-e-w** [comment]
- https://github.com/nicholas-ooi/stable-diffusion-database-manager/pull/2

**Comment by w-e-w** [comment]
sorry I forgot to merge this to index

**Pull request merged**
