### PR TITLE
lots of extensions by Haoming02

### PR DESCRIPTION
**Pull request by w-e-w**
## Info 
bunch of extensions by Haoming02 to review when I have time
- https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/247

## Checklist:

- [ ] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [ ] The description is written in English.
- [ ] The `index.json` and `extension_template.json` have not been modified.
- [ ] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by w-e-w** [comment]
> "Moar Generate Button" is nice. Use it every time

you konw about `ctrl + enter`?

**Comment by w-e-w** [comment]
@Haoming02 is there a particular extension that you would like to or prefer not to be added to the index?

**Comment by w-e-w** [comment]
> > > "Moar Generate Button" is nice. Use it every time
> > 
> > 
> > you konw about `ctrl + enter`?
> 
> Hotkeys are inconvenient because almost all interaction with a wall of extentions accordions is processed with mouse

don't people usually have one hand on the keyboard the other hand on the mouse?

**Comment by Haoming02** [comment]
The followings are probably worth adding to the index as well:

[Mosaic Outpaint](https://github.com/Haoming02/sd-webui-mosaic-outpaint)
```json
{
    "name": "Mosaic Outpaint",
    "url": "https://github.com/Haoming02/sd-webui-mosaic-outpaint.git",
    "description": "Outpainting without ControlNet",
    "tags": [
        "tab"
    ]
}
```

[SD Webui Image Comparison](https://github.com/Haoming02/sd-webui-image-comparison)
```json
{
    "name": "SD Webui Image Comparison",
    "url": "https://github.com/Haoming02/sd-webui-image-comparison.git",
    "description": "Easily compare img2img results within the Webui",
    "tags": [
        "tab"
    ]
}
```

As for not adding, is the **Mobile Friendly** one worth keeping? I originally wrote it for someone on Reddit. Not sure if it's that useful, especially since I haven't updated it for some time now...

**Comment by Haoming02** [comment]
Btw in case you missed it, the **Easy Tag Insert** entry seems to be unfinished:
```json
{
    "name": "Easy Tag Insert",
    "url": "https://github.com/Haoming02/sd-webui-easy-tag-insert.git",
    "description": "Button shortcuts for user-specified prompts",
    "tags": [
        "prompting"
    ]
}
```

**Comment by w-e-w** [comment]
> Btw in case you missed it, the Easy Tag Insert entry seems to be unfinished:

thanks

> [SD Webui Image Comparison](https://github.com/Haoming02/sd-webui-image-comparison)

cool, I also have a image comparison extension I wrote for personal use myself

I need to find time the go though the extensions, I'm kind of procrastinating to be honest

**Comment by w-e-w** [comment]
@Haoming02 I thested all extention listed on this PR
all seems to work but
sd-webui-easy-tag-insert is broken in 1.8
- https://github.com/Haoming02/sd-webui-easy-tag-insert/pull/6
I make a quick PR to stop it from crashing but is stille break 1.8 extra networks tab so is still doesn't worlk so I remove is from this PR for now
after it's fixed it can be added in a separate PR
- https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/286

**Pull request merged**
