### PR TITLE
Update stable-diffusion-webui-wd14-tagger.json

### PR DESCRIPTION
**Pull request by picobyte**
Credits for Toriato for his work, but his extension has been inactive, with some issues. I had a pull request for a while, and it has been growing, to the extent that some suggested me to just create a main branch and present it here. See my last reease notes here for the updated changes list:
https://github.com/picobyte/stable-diffusion-webui-wd14-tagger/releases

And a prior discussion:
https://github.com/toriato/stable-diffusion-webui-wd14-tagger/pull/93

I am hospitalized for a few days, so I may not be able to respond in a few days - patch/fix for a cycling tourist collision, handling a mobile phone

### CODE REVIEW

**Comment by ClashSAN** [comment]
ty @picobyte !
We add this in 1 week since toriato doesnt have github activity in 4 months.

**Comment by w-e-w** [comment]
let resolve the conflict when the time comes
the conflict is due to git not able to cope with the vast amount of changes done to the index because the introduction of metadata metadata to the index
this should not happen again after subsequent for commits

**Comment by w-e-w** [comment]
should we reset added date?

**Comment by ClashSAN** [comment]
Its weird because it will end up at the top with increased visibility. We should keep the legacy order or else people will wrongly view the new extension by stars.

I can try to find the original submission data's of forked extensions and put them back with a PR

**Comment by w-e-w** [comment]
the current automation is such that the origin date will be kept and internal order of the extension index will be kept

the added date will be filled with the current date if the date is missing (this is what happens to new entries)

new extensions will be added at the bottom
the identifier is based on the URL
so if a extension has a change of URL it will be moved to the bottom of the list

**Comment by ClashSAN** [comment]
Create time is the creation date of the repository?

**Comment by w-e-w** [comment]
there is 3 time
added time the time that it's been added to the index, this is a local value that we set

commit_time the commit time of the default branch of the repo, the uodate time
created_at the create time of the repo
these 2 values are from github's api

**Comment by ClashSAN** [comment]
We keep the "images browser" extension legacy added date at 2022, despite the fork. The forks creation is 2023.

We should probably keep everything like images browser, we can fix the improper dates set manually.

**Comment by w-e-w** [comment]
you can set the date manually
it only auto fills the added date when the date is invladi / not found
or are you talking about the 2 other dates?

**Comment by ClashSAN** [comment]
- It is preferable that people submitting do not change the date
- It is important to me to keep the primary (non-fork's) added date

**Comment by w-e-w** [comment]
> I don't think so.
> 
> * It is preferable that people submitting do not change the date
> * It is important to me to keep the primary (non-fork's) date: (the "added" section)
>   
>   * some replacement forks changed the date, we can change it back manually.

sure if you think of necessary, I have no strong objections
the only thing that I was considering was that maybe moving it up the list and people might notice and change to the fort so that they can receive new updates

> hmm maybe we can possibly build this in to webui

if you want to modify the date you can edit the entries in the exchange directory, don't change it in index,json

on the other hand if you wish to modify the order of the extensions in the index.json, then edit the index directly

the order of index.json doesn't change upon build and metadata update

these are 2 extensions that I remember have uodate the added date when updating URL
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/94
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/79

**Comment by ClashSAN** [comment]
@w-e-w 

There is one extension: sd-webui-color-enhance
that is outside github. It will have no metadata

**Comment by w-e-w** [comment]
I was the one who approved that extension
I built the metadata action to skip non GitHub repos

**Comment by picobyte** [comment]
Thank you for the responsibility. I must say I didn't fully understand what the replies were about, I'm guessing you were just discussing extension intrinsics; comments that were not for me, but if there is anything I still need to do or change, let me know or just point out which comment was relevant. I've enabled issue tracker discussion and wiki on my fork of the tagger project.

**Comment by w-e-w** [comment]
ahhh
actually pretty much none of the conversation pertains to you
we're just using this place as discussion for something else

they run down is that we were going to wait for around a week before changing to your fork, but then the original offer replied so I just merge the change immediately

**Pull request merged**
