### PR TITLE
add sd-webui-workspace

### PR DESCRIPTION
**Pull request by Scholar01**
## Info 

Designed to save and restore Webui workspace. It can quickly save your current webui interface and restore it the next time you use it.

## Checklist:

- [x] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [x] The description is written in English.
- [x] The `index.json` and `extension_template.json` have not been modified.
- [x] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by w-e-w** [comment]
typo workscace -> workspace
https://github.com/Scholar01/sd-webui-workspace/blob/master/workspace/workspace.py#L46C94-L47

also I would advise not to save `workspace.json` under webui root
this at the very least is an annoyance and can cause issues in future
save it under your extension directory instead, and add it to your `.gitignore`
a fix PR for the above
https://github.com/Scholar01/sd-webui-workspace/pull/1

other issues
from a quick test but I believe if you have some extension that has a gallery component such as controlnet it that allows you to input an image
if you try to save the workspace with a image loaded in controlnet, this the breakes the extension, see img and error log
considering the large amount of users that uses controlnet do you want to add an extension this state?
if you do I will add the extension to the list


https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/assets/40751091/b34d5f8c-94d8-4a82-8811-75dd2cd06b39

image
image

```shell
Traceback (most recent call last):
  File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1326, in postprocess_data
    prediction_value = postprocess_update_dict(
  File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 460, in postprocess_update_dict
    prediction_value["value"] = block.postprocess(prediction_value["value"])
  File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\gradio\components\image.py", line 314, in postprocess
    return processing_utils.encode_array_to_base64(y)
  File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 104, in encode_array_to_base64
    pil_image = Image.fromarray(_convert(image_array, np.uint8, force_copy=False))
  File "B:\GitHub\stable-diffusion-webui\venv\lib\site-packages\gradio\processing_utils.py", line 416, in _convert
    raise ValueError("Images of type float must be between -1 and 1.")
ValueError: Images of type float must be between -1 and 1.
```
webui version: [v1.6.0-209-g7d60076](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/7d60076b8b275771a1aa98f017aff845ef68d964)
controlnet v1.1.410

**Comment by Scholar01** [comment]
Firstly, my gratitude for your rectification. I have just amended an error concerning the importation when the Image type is numpy. Presently, it operates seamlessly. However, a minor imperfection lingers: should a file be imported while the Accordion is closed, it necessitates a click on the image refresh button to display. I shall ponder a resolution to mend this shortly.

**Comment by Scholar01** [comment]
I may require some testing, as numerous errors persist; I shall initiate a merge request subsequently. Once again, thank you!

**Comment by w-e-w** [comment]
cool
btw when addind the the index, don't add the added date
```json
"added": "2023-10-04"
```
this will be filled automatically by the GitHub action

**Comment by w-e-w** [comment]
any progress on your extension?

---

just to let you know someone is working on a similar extension
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/248

**Pull request closed without merging**
