### PR TITLE
Redirect stable-diffusion-webui-stable-horde.json

### PR DESCRIPTION
**Pull request by w-e-w**
## Info 

the origin repo was most likely deleted by the author redirecting to upload clone
```diff
-   https://github.com/natanjunges/stable-diffusion-webui-stable-horde.git
+   https://github.com/w-e-w/stable-diffusion-webui-stable-horde.git
```

## Checklist:

- [ ] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [ ] The description is written in English.
- [ ] The `index.json` and `extension_template.json` have not been modified.
- [ ] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by w-e-w** [comment]
@natanjunges
Hi was there a reason for the deletion of the natanjunges/stable-diffusion-webui-stable-horde repository around 20241014

**Comment by natanjunges** [comment]
It has been archived since July last year. I don't have the time or the interest to maintain it, so feel free to do so if you want.

**Comment by w-e-w** [comment]
ok thanks for the answer
to be honest I never used stablehorde and pretty much forgot about its existed until now
I've only noticed that the repository has been taken down because of error meessage form the action
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/actions/runs/11321632801

my intention is to just put the repository up so that if people actually wish to download it can find it
I'm not even sure if it works but it's there if they want, maybe someone in the future would decide to maintain it

Thanks for your work

**Comment by w-e-w** [comment]
I've added a notice to the readme about the status of the repo
Thanks

https://github.com/w-e-w/stable-diffusion-webui-stable-horde/commit/c9de9b8db8c52d3650c8c82c869bed091a525803

**Pull request merged**
