### PR TITLE
Add SD Model Organizer

### PR DESCRIPTION
**Pull request by alexandersokol**
Hello!
Just finished creating a new extension and would like to add it to the general index.

The main goal is to add some user-friendly UI to manage information about models, add own notes and download/remove files.

You can find all information in the README file in the repo.
https://github.com/alexandersokol/sd-model-organizer

### CODE REVIEW

**Comment by w-e-w** [comment]
some clarification and issues I found
clarification 
```
even though you read me makes it seems like so, this is not a civitai integration
this is a extension for downloading models from **any external url** with optional preview image based on entries made by the user manually
with option to fill in other information such as preview image, original model web page and  any other notes that the user would like to add
supports for searching your models by grouping and tags Etc
```
is this correct

some issues I found

1. the preview image doesn't seem to be locally cached, which means it will need to make request to external server to fetch image causing unnecessary strain
2. you seem to be using the wrong path for the models
it is common practice to change the ckpt path 
see https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings
`--ckpt-dir`
there are also many other parts not just the sd checkpoint
3. after I have downloaded file there's an error saying that it's being used by some other process or something
however I don't think this is an issue, since the model is moved to the `internal model folder` `wrong location`

this extension is broken
the extension will have to be working in order for it to be added. and I consider this to be broken

**Comment by alexandersokol** [comment]
Hi!
Yes, your clarification is correct, I might update readme then, because all sample models there from civitai and users might be confused. 
1. Will update it
2. Will check it.
3. Can you share what OS are you tested on? Looks like it is something system-specific. I will check it too.

Thank you for the review!

**Comment by w-e-w** [comment]
windwos 11
chrome
python: 3.10.6  •  torch: 2.0.0+cu118  •  xformers: 0.0.17  •  gradio: 3.28.1  •  commit: [5ab7f213](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ab7f213bec2f816f9c5644becb32eb72c8ffb89) 

`--ckpt-dir drive:\some\path`
I only tried downloading one sd checkpoint
but I assume other types of models will have similar behavior

**Comment by alexandersokol** [comment]
Hello!

- Updated extension description.
- Added "online" tag.
- Fixed download error.
- Command arguments like `--ckpt-dir`, `--vae-dir`, `--lora-dir`, `--hypernetwork_dir`, `--lyco_dir`, `--embeddings_dir` now have top priority of defining models destination directory in case nothing else was set manually in settings menu.
- temp files during download are now placed in the destination dir to prevent moving huge files across different disks.

**Comment by w-e-w** [comment]
after a quick test it seems to be working

**Pull request merged**
