### PR TITLE
Update index.json

### PR DESCRIPTION
**Pull request by razorback456**
Ukrainian localization

I tried not to translate terms and proper names, but to translate only tips and explanations

### CODE REVIEW

**Comment by w-e-w** [comment]
url 404

**Comment by w-e-w** [comment]
you have another repo https://github.com/razorback456/ua_UA-stable-diffusion-webui
but that is not a localization

**Comment by razorback456** [comment]
> you have another repo https://github.com/razorback456/ua_UA-stable-diffusion-webui but that is not a localization

yes, sorry, I must have mistaken the link https://github.com/razorback456/webui-localization-ua_UA

**Comment by razorback456** [comment]
> you have another repo https://github.com/razorback456/ua_UA-stable-diffusion-webui but that is not a localization

the correct link is https://github.com/razorback456/webui-localization-ua_UA
everything works fine for me, I don't know why you have an error

**Comment by razorback456** [comment]
> url 404

I fixed the error.

I accidentally wrote 'webui-localization-ua_UA' twice

everything should work now

**Comment by w-e-w** [comment]
the still does not exist a repo at https://github.com/razorback456/webui-localization-ua_UA
also I don't see any localization repository under your account
I have no idea what you're doing
reopen this request when you do have a localization ready

**Comment by razorback456** [comment]
> there is still does not exist a repo at https://github.com/razorback456/webui-localization-ua_UA also I don't see any localization repository under your account I have no idea what you're doing reopen this request when you do have a localization ready

sorry, I'm new to github
I forgot to set the repository visibility to 'public'

now i fixed it i think you should see the repository.

**Pull request closed without merging**
