### PR TITLE
Add sd-webui-GPT4V-Image-Captioner

### PR DESCRIPTION
**Pull request by SleeeepyZhou**
## Info 

This is an SD WebUI plugin version of the GPT4V Image Captioner, a multifunctional image processing toolbox built with Gradio, capable of tagging images using the GPT-4-vision API. MLLM APIs including but not limited to GPT4V can be used. And some tag editing and tag analysis tools. 

My project address 
https://github.com/SleeeepyZhou/sd-webui-GPT4V-Image-Captioner
and original project address 
https://github.com/jiayev/GPT4V-Image-Captioner

Thank you for the review. 

## Checklist:

- [x] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [x] The description is written in English.
- [x] The `index.json` and `extension_template.json` have not been modified.
- [x] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by w-e-w** [comment]
I don't have a chat GPT-4 subscription
and I believe in order to obtain an API key you need a paid subscription correct?

if this is the case I think is best to add this information to the description

since I don't have a subscription I cannot test if this is working myself
can you send a screenshot or video demonstrating that the extension is working

**Comment by SleeeepyZhou** [comment]
At present, it can only work through the paid GPT4V API, as there are some compatibility errors that need to be fixed in the COG based local API. Therefore, the GPT4V version will be submitted for use first.

The following is a picture of me working with the local CogVLM API.

image

**Comment by w-e-w** [comment]
tip, depending on your use case you can add a `Setting` to store you api key

the advantage of using settings is that it can be shared across entire instance
the advantage of using a UI input box is that different users can use different keys

**Comment by w-e-w** [comment]
does this look okay to you
```json
{
    "name": "GPT-4 Vision Image Captioner",
    "url": "https://github.com/SleeeepyZhou/sd-webui-GPT4V-Image-Captioner.git",
    "description": "This extension utilizes the power of GPT-4 Vision API to provide image captioning capabilities through the Stable Diffusion Web UI. Requires a paid subscription to OpenAI.",
    "tags": [
        "tab",
        "online"
    ]
}
```

**Comment by SleeeepyZhou** [comment]
Thank your support!

**Pull request merged**
