### PR TITLE
Create Gigagrid

### PR DESCRIPTION
**Pull request by yggdrasil75**
## Checklist:

- [x] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [x] The description is written in English.
- [x] The `index.json` and `extension_template.json` have not been modified.
- [x] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by w-e-w** [comment]
@yggdrasil75

generally we don't add forks if the original is still working, unless the fork is different enough as to become its only porject 
I have't chacked but it seem @mcmonkey4eva version is still working last update was 4 days ago, so the fires condiction is not meet
your description "Replaces older version by MCMonkey" seems to also imply mcmonkey4eva is somewhat "out of data" or "borken" which dose not seems the case

I seems you did make lost of changes (form readme, not tested my self), but have you makeing a PR to the upstream branch
we perfer people to collaborate

and if this is going to be added, it can not be under the same repo name `sd-infinity-grid-generator-script`, this will cause one not able to be installed as it shares the same dir (unless manually renamed)
you have to change yor repo name to something else

@mcmonkey4eva your opinion?

**Comment by mcmonkey4eva** [comment]
Context is this user made several bad changes and PRs that introduced bugs stemming from misunderstandings of the original code, and when I pointed out that their code wasn't actually correct, they got upset and started a fork and started pushing people to use that, and then in the past few days began spamming the issues page of the original extension telling people to use their fork, and accordingly I blocked them from the repo.

I strongly suggest closing this PR.
In the event the PR is not just entirely closed, I request the title & description be changed to not reference Infinity Grid or my name in any way.

**Comment by mcmonkey4eva** [comment]
You made 5 comments to 5 different issues on infinity grid all at once, every single one of those comments was telling somebody that your fork had something.

Your PR https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/pull/48 was rejected because the code in it does not make sense. You just copypasted spammed axes, to accomplish a thing that could already be done without code changes. The core concept (allowing numbers in addition to spaces to repeat params) was added using better code later on when it was actually communicated what/why it was wanted.

Your PR https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/pull/45 was rejected because it does not make sense. You gitignored the Github folder... you can't do that, that folder is there for a reason. And, once again, your PR did not clearly explain at all what it was or why you were doing that. The typo you found in that PR was fixed immediately after you showed it.

Your comments on https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/issues/99 made an incorrect claim about what a line of code did, and then in your fork you deleted that line of code due to your misunderstanding, and I replied trying to correct your misunderstanding of it.
None of the comments you made in that thread, or any other, were posts oriented towards improving the project in a productive manner, they were all pushing your fork.

---

Consider for comparison eg the PRs made recently by skfoo https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/pulls?q=is%3Apr+is%3Aclosed+author%3Askfoo , who made a variety of successful pull requests for various features and bugfixes.

Or consider these PRs from another user <https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/pull/77> <https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/pull/80> where the PRs were imperfect, and in fact that user's first PR was rejected for code issues, but the ideas were reasonable and well-communicated, and the user took no offense at a rejected PR and happily made a new PR for the next thing that came up.

If you can submit PRs in a manner better resembling these positive examples, I'll happily unblock you and take future PRs from you.

**Comment by w-e-w** [comment]
since 24 hours have passed since the last message from either of you I take it as a sign that both of you have said what you want

---

before I explain my viewpoint in judgment and decision-making process I have to disclose my bias to the situation 

first I have interactions with [mcmonkey4eva](https://github.com/mcmonkey4eva) in the past, I do not know him in person but have spoken via text through Discord GitHub, from what I know of him I consider he being a trusted member of the community, and has a traceable background connection to the real world, this means his words here I could have an impact on his real life, he also has taken some important roles such as moderator Reddit Discord in the community, I do not profile him as one that would spread lies or be an impulsive person and has helped to review extensions in past, suffice to say that I take what mcmonkey4eva with a level of trust

on the other hand, I don't recall I have interactions with [yggdrasil75](https://github.com/yggdrasil75) before this, and things get a little bit worse as my first impression of the initial PR [a14f5d6](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/207/commits/a14f5d68faa2ae0b8b68fa9a2ba678f67f784576) is not great, I've expressed this in my initial [comment](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/207#issuecomment-1765774129)


I classify my perspective on this situation including development usage and understanding of this extension as more "outsider" one, I don't use this extension much myself and do not know much about its advanced usage, I've only contributed once to fix a minor issue caused by a certain behavior of web UI

my perspective on the role of the extension index is to provide an easy-to-access way for users to download and install extensions and for developers to showcase and share their extensions.
due to the large user base of web UI this has somewhat become an advertising platform unavoidably

---

my general guideline is that if an extension is "beneficial" it can be added to the index

based on his guidelines I have said some rules
1. Extension must be without major issues to be listed (at least at the time of review), either security issues or breaking issues that prevent extensions from working. When reviewing an extension, I would do a quick review of the code base and test if the extension works as intended.
2. An extension should achieve a certain level of quality / polishness, this is a list that will be used by general users.
3. I have a policy of not adding forks or other extensions that serve an extremely similar purpose, the reason being that I believe this helps develop the original extension as I believe encourages people to contribute and continue maintaining and improving an extension, as opposed to have a constantly growing list of similar extensions that might be quickly deprecated.
4. In the event that a main extension is broken, and a suitable fork exists, the index will divert people to download the new extension. 
5. in cases where the original extension is not broken, but a fork has already developed substantially, but the changes cannot get merged in the root extension (got rejected or due to non-responsiveness), it can be considered to be added to the index.
6. the description of the extension, should clearly describe what the extension does, description should be clear and discreet and should not demean on other extensions.
7. in certain cases I will require extension to have sufficient documentation in its before it can be listed

note this is not a complete list, these are just the parts I was able to put into words at the moment

---

regarding the issue at hand

when reading the initial description, my take on this is that this is an attempt to replace or suppress the origin extension, which as far as I can tell the origin is still in working condition and is still being actively developed
especially in the phrasing, "Replaces older version by MCMonkey", looks very bad to me
adding to the fact that the front portion of the description is just a copy-paste of the original
I see this in a very bad light

this extension to me does not fulfill 3. and 4. and violates 6. I would not approve this extension in the state, and I want to see if I can categorize this as 5.
this is why I just by looking at the pull request I decided to Ping mcmonkey4eva to see what's going on.

and let's just say we have some "drama", and it seems the chances of you two working together are low

I also do not think I'm in a position where I should intervene in a relationship between you and how you two decide to develop.

I will “Not” request mcmonkey4eva to unban yggdrasil75 but it is my hope that fellow developers will work together, that's all I will see on this matter.

---

now the question is can this be categorized as 5., 

> 5. in cases where the original extension is not broken, but a fork has already developed substantially, but the changes cannot get merged in the root extension (got rejected or due to non-responsiveness), it can be considered to be added to the index.

mostly based on https://github.com/yggdrasil75/Gigagrid#this-fork

> Full path specification (if you put f:\path\to\whatever then the output will be there, instead of automatic\grids\whatever)

I consider this a minor preferential change, and it's something that can be implemented easily origin extension if necessary, maybe they're also reasons not to do so but I do not know.

> full or partial path specification in the grid file via "outpath"

to be honest I'm not entirely sure what this means, if possible add better documentation on what you mean by that

> piecemeal skipping via "title" specification and "params" less specifically. allowing you to ignore certain combinations without skipping an option completely.

I remember reading something about skipping, in the original extension, maybe I already implemented I could be wrong if so please correct

> Batching: batch size is optional as either yaml or via gui. the yaml will override the gui as normal. key is "batch size". you can run it with more than the gui batch size (I run it at 10 for my 512x512. on a better card you could do 20 possibly)

this also look like something that could be useful in some cases, but I believe this is also a minor change that can be implemented easily.

> Numeric prompt replace: you can use "prompt replace 1" up to "prompt replace 9" as keys (with spaces) to make it easier to specify the various prompt replaces. now you can organize them more naturally. (included in base since adding to here.)

> Negative Prompt Replace: you can use "n prompt replace" or "negative prompt replace" (with negative allowing 1-9 similar to normal.)

for these two based on [this comment on the PR](https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/pull/48#issuecomment-1478782063
), it should already be possible just done differently, is totally possible that I misunderstands the use case as I don't use it myself, but due to this I do not consider this a future just a different way of doing things, makes it easier I'm not sure

based on my assessments of the changes from your description I do not consider your extension to be a substantial fork

and so I do not approve of listing this extension on the index

---

can you reapply it to be listed in the future, Yes.

if in the future there is substantial development in your fork as to make it an extension that actually provides more /function/use cases/based on different ideologies and goes in mind... etc as to become a different extension.
if the extension satisfies these requirements it can be listed

There also needs to be sufficient documentation proving that it is a substantial fork

**Due to this situation at hand I would add one additional condition**

as mentioned by mcmonkey4eva in 
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/207#issuecomment-1767043170

> In the event the PR is not just entirely closed, I request the title & description be changed to not reference Infinity Grid or my name in any way.

I believe this request is totally reasonable, and mcmonkey4eva should have the right to review the description

---

@yggdrasil75 do you agree with my ruling on this matter, do you believe that I have been unfair in any part of the reasoning, if so please point them out, if you believe that I have made certain misjudgments on certain aspects please Point them out, if you believe that I'm biased we can find other people to judge the situation to have a second opinion

@mcmonkey4eva do you agree with my ruling on this matter, do you believe that I have been unfair in any part of the reasoning, if so please point them out, if you believe that I have made certain misjudgments on certain aspects please Point them out, if you believe that I'm biased we can find other people to judge the situation to have a second opinion

hopefully, I haven't soured my relationship with any of you and I have acted in a neutral manner

**Comment by mcmonkey4eva** [comment]
You've clearly gone far out of your way to handle this as professional and unbiased as possible 👍 

-----

for the record as stated earlier `If you can submit PRs in a manner better resembling these positive examples, I'll happily unblock you and take future PRs from you.` - I'm happy to unblock yggdrasil from the infinity grid repo if they can just make an effort to contribute in a less hostile manner.

**Comment by mcmonkey4eva** [comment]
`Full path specification` this can be easily added if desired, it has to my knowledge never been requested.

`I then added an option to the yaml which will be used if nothing is specified in the ui so you don’t have to type it out each time. (outpath)` there's already defaulting that prevents the need to type it out - having the file specify an alternate path could easily be added, but again, never requested.

`piecemeal skipping is not overly simple` true, not simple, and in this case has actually been requested. Would be interested in a PR for this.

`Batching is a lot harder` intelligent autobatching (ie apply batching exactly where it can be automated while still avoiding all the side effects and edge cases) has been on my todolist for a while, but the reason it's quite low is `with 1 batch that takes 5 minutes than 36 singles that takes 1 minute each` this ratio has never held remotely close to true in any context i've seen - large batches at the best of times with SD only get a percentage performance boost (eg batch of 5 images in 20 seconds vs 5 individual images at 25 seconds), with large modern images (SDXL or highres fix) batching performance improvements are miniscule and hard to justify spending dev time on (10% or less, with little room to scale to higher batch due to VRAM constraints). Willing to consider a carefully crafted PR for it though.

`Numeric prompt replace was my second pr, it was denied as being pointless, but it was implemented anyway.`
This is somewhat correct but misleading phrasing, so I'll repeat:
`Your PR https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/pull/48 was rejected because the code in it does not make sense. You just copypasted spammed axes, to accomplish a thing that could already be done without code changes. The core concept (allowing numbers in addition to spaces to repeat params) was added using better code later on when it was actually communicated what/why it was wanted.`

`Negative prompt replace is basically the same thing as normal prompt replace, it just makes it so that you don’t replace a word in both positive and negative. This is not possible in the origin, but would be quite easy to implement.`
I'm not sure the point of this (why do you have the same phrases in both positive and negative prompt?!) and it's never been requested, but yes it'd be easy to add if ever requested with a valid reason.
\*There's also still a way to implement this in a grid regardless by using intentional trigger phrases (ie have the negative prompt explicitly use a phrase that won't be reused as the replace target, or even use a placeholder like `my negative, {replace-1}, etc` and then just `{replace-1} = my negative phrase`)

`which makes the path names be properly consistent based on your os. (1 example. There is a lot)` the behavior of replacing backslashes to forward slashes was an intentional normalization between OS's (everything should behave the same regardless of whether you are working on Windows or Linux! Normalization helps ensure this)
(FTR: I _am_ a professional developer, with 15+ years experience, and I have gone through hell and back with cross-OS compatibility issues from code that doesn't normalize line endings over the years, handling it is always weird but I've arrived on relying on this normalization method as being the best way through lots of trial-n-error and working in a variety of contexts with a variety of people) (note that `/` is a valid path separator everywhere, but `\` is unique to windows. Ie a stray `\` getting left somewhere will break Linux/Mac/Android/iOS/..., but using `/` constantly is fine on any/every OS)

`I have added timing (an issue I posted on the origin but was told that it was pointless. The claim was every model is the same time per image no matter what.)` That is in reference to this issue: https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script/issues/46 and I fully stand by my responses there. (With the exception that with the advent of SDXL, there are now _two_ model performance classes - SDv1 and SDXL perform differently, but finetuned models within a class are identical)
(note that nowhere in your issue do you mention resolution/etc - you were very specific about models and samplers)
This speaks to the repeated root issue here: you have fundamental misunderstandings of the backing technology and seem inclined to write code first, ask questions later, and thus write broken code\*. You need to slow down and understand the underlying technology before changing it.
(Or, at least, recognize this pattern in yourself, and work to respond gracefully when it's pointed out where your understanding was flawed)

---

`If Monkey is willing to take my prs and merge them or partial merge them if they do not suit his style instead of close and implement on his own, then I would also need to know what prs would be willingly accepted.`
To be pulled, a PR must (A) have a clear purpose (ideally a linked issue), (B) functionally achieve its goal, and (C) be either fully correct code, or at least close enough to correct that it can be slightly amended and then pulled.

The PR that copypasted prompt replace registration 10 times failed on (A) (it was not clear in purpose at the time, I only learned your intent later), and (C) (it was copypasta, if it was merged the next commit would just be immediately removing it and redoing it from scratch), but did more or less get (B) at least

The PR that `gitignore`'d the `Github/` folder fails all 3 points (no clear purpose, functionally did nothing, was not correct code)

`Would the batching pr be accepted as it is the biggest speed benefit for this script?`
It passes (A) and presumably you'll test and ensure it passes (B), so it comes down to whether the PR passes (C). I can work with you to help get it there if you're unsure of how to write it well.

`Would the caching be accepted?`
Not sure what this refers to?

`Would replacing string comprehension with os.path be accepted?`
No, fails requirement (A) - what is the purpose? That's just breaking intended compatibility code.


`If you [...] unblock me`
I've gone ahead and removed the block.

**Comment by w-e-w** [comment]
glad to see you guys communicating

**Comment by mcmonkey4eva** [comment]
image

**Comment by w-e-w** [comment]
PR's to this Repository should be only used as a request to add extension to the index
this station has already been rejected based on reasons mentioned above
since then till the time that this PR is reopened there hasn't been any development of the extensions repository
in other words there should be no reason to reopen this PR
> we only care about the main branch as it's the branch it will be installed

adding to the situation based on the reopened message and some other messages that are available to me
I've concluded that this reopening is merely a expression of anger and an attempt to drag a third party into the mud
in other words this is spam
> if you consider a single message and reopening of this PR is not enough to be not spam, then this means that you have underestimate the seriousness of the situation and the effort involved

when an extension is added to index, even though we do not provide any guarantees or have any responsibility of what the extension does, the mere fact of it beeing listed on the index by us meant that we bestow a certain level of trust to a project and it's maintainer
> we're essentially giving someone the power to have their code delivered and executed on someone else's computer

in open source development "Communication" and "Trust" is it very important if not the most important factor

from my perspective communication has failed and based on the messages I subjectively cannot trust the author of this PR

this PR will be closed and the conversation will be locked to prevent escalation of the situation

**Pull request closed without merging**
