### PR TITLE
Update index.json

### PR DESCRIPTION
**Pull request by limithit**
Add an extension to change the background for png images

### CODE REVIEW

**Comment by ClashSAN** [comment]
@limithit hi, add a new json with your extension  URL title in the extension folder.
the automation system needs you to do things that way, or things can break.

**Comment by w-e-w** [comment]
in this case it wouldn't break
the entry would just be automatically removed

**Comment by w-e-w** [comment]
I could fix it for you but like the description really is very unclear and do you really want to call it Gandalf

**Comment by limithit** [comment]
@w-e-w Yes, I don't know much about the process. I'm sorry.

**Comment by w-e-w** [comment]
> @w-e-w Yes, I don't know much about the process. I'm sorry.

well next time try reading https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions#how-to-submit-extension
I think my instruction is quite clear

**Pull request closed without merging**
