### PR TITLE
sd-webui-inpaint-anything

### PR DESCRIPTION
**Pull request by w-e-w**
add sd-webui-inpaint-anything
https://github.com/Uminosachi/sd-webui-inpaint-anything
@Uminosachi
we received a request to add your extension https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/issues/82
can you confirm if the description and the tags are to your liking

### CODE REVIEW

**Comment by Uminosachi** [comment]
Please utilize the description and tags provided below. If "inpainting" cannot be applied as a tag, please use "editing".

"description": "The Inpaint Anything extension performs SD inpainting, cleaner, ControlNet inpaint, and sending a mask to img2img, using a mask selected from the segmentation output of Segment Anything."
"tags": ["tab", "inpainting"]

**Comment by w-e-w** [comment]
to be honest the tag system doesn't make sense to me
currently it is used as a thing to hide extensions instead of categorizing
I hope in the future we could change it so that it's used to select certain categories of extension instead of the other way around
because of this currently I don't think it's a good idea to add it extra category
if in the future we flipped out the system worked in web UI then we could a new tag

**Comment by w-e-w** [comment]
description has been updated

**Comment by Uminosachi** [comment]
Could you please use the tags provided below?

"tags": ["tab", "editing", "manipulations"]

**Comment by w-e-w** [comment]
I made the Tag changes

I really should have asked you to just make a PR this way you can edit it directly
if you're not okay with this fork this and make if you are and adjust to your satisfaction

**Pull request closed without merging**
