### PR TITLE
SD Simple Dimension Preset

### PR DESCRIPTION
**Pull request by gutris1**
## Info 
https://github.com/gutris1/sd-simple-dimension-preset

## Checklist:

- [x] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [x] The description is written in English.
- [x] The `index.json` and `extension_template.json` have not been modified.
- [x] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by w-e-w** [comment]
again here your description is being used as readme documentation it is not supposed to be a documentation

don't copy your readme
- https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/394#issuecomment-2561381729

**Comment by w-e-w** [comment]
also PR to fix to an issue
- https://github.com/gutris1/sd-simple-dimension-preset/pull/3

**Comment by w-e-w** [comment]
one suggestion
> I want to be clear that this is a personal "suggestion" NOT a requirement

for the SVG icon yor are using `--primary-500` as the color
in my opinion does not work that well on most themes
it stands out quite a lot and very different from the `switch width / height` Icon below it
I would suggest that you use the same color color as the icon whitch is `--button-secondary-text-color`

hear is 3 themes side by side comparisons ligh and dark mode
I was suggest that you test morphemes to see what works best

| `--primary-500` | `--button-secondary-text-color` |
|--------|--------|
| 2024-12-25 08_48_17_134 chrome | 2024-12-25 08_52_06_979 chrome |
| 2024-12-25 08_48_47_102 chrome | 2024-12-25 08_52_00_872 chrome |
| 2024-12-25 08_49_33_811 chrome | 2024-12-25 08_51_06_272 chrome | 
| 2024-12-25 08_49_40_335 chrome | 2024-12-25 08_50_54_324 chrome | 
| 2024-12-25 08_58_34_794 chrome | 2024-12-25 08_52_31_202 chrome | 
| 2024-12-25 08_59_02_890 chrome | 2024-12-25 08_52_37_888 chrome |

**Comment by gutris1** [comment]
> one suggestion
> 
> > I want to be clear that this is a personal "suggestion" NOT a requirement / issue
> 
> yor are using `--primary-500` for the SVG icon color in my opinion this does not work that well on the themes I tested it stands out quite a lot and very different from the `switch width / height` Icon below it I would suggest that you use the same color color as the icon whitch is `--button-secondary-text-color`
> 
> hear is side by side comparisons of 3 themes ligh and dark mode I was suggest that you test more themes to see what works best
> 
> `--primary-500`	`--button-secondary-text-color`
> 2024-12-25 08_48_17_134 chrome	2024-12-25 08_52_06_979 chrome
> 2024-12-25 08_48_47_102 chrome	2024-12-25 08_52_00_872 chrome
> 2024-12-25 08_49_33_811 chrome	2024-12-25 08_51_06_272 chrome
> 2024-12-25 08_49_40_335 chrome	2024-12-25 08_50_54_324 chrome
> 2024-12-25 08_58_34_794 chrome	2024-12-25 08_52_31_202 chrome
> 2024-12-25 08_59_02_890 chrome	2024-12-25 08_52_37_888 chrome

haha, I only tested it with nocrypt theme and gradio default
I'll change it

**Comment by gutris1** [comment]
thanks a lot.

**Comment by w-e-w** [comment]
I change the `script` tag to `UI related`
like most other `Aspect Ratio` extentions

**Comment by gutris1** [comment]
hey @w-e-w , if I may
whats your opinion on this one? https://github.com/gutris1/sd-image-viewer

**Comment by w-e-w** [comment]
my opinion
it's a gigantic block of code with no descriptions apart from a title and a screenshot
and commit messages only readable by people who understand emoji
image

if you want to actually give feedback about your code, you will want to get adequate information making 
other people's life easier

---

after reading the WALL OF TEXT bit, and determined that it seems to be only DOM manipulations
and so should be safe to execute, I then installed your extension on my system

it "SEEMS" to work that is ALL I can say
I can't know if it's actually working because I didn't bother entire reading the code
there could be some important functionality not working, but because it's not working I don't see it working so I don't know if it's working or not

all "I know" is that I "LOSE" functionality such as the ability to toggle live preview
image

### !!! provide documentation before asking people to review !!!
otherwise people won't even know that this is supposed to be a full screen image viewer that replaces the
> I know what this is because I recognize some of the code that you use such as `lightboxModal`

---

## BUG
you forgot to decode the downlaod file names from URL encoding
`20241228-013828-535525%203167095102%201ea5.png` -> `20241228-013828-535525 3167095102 1ea5.png`

---

for you info there is this https://github.com/viyiviyi/stable-diffusion-webui-zoomimage

I'm not saying this extension is perfect
I personally have one issue with it, I don't like the image that's not take up the full height of the window
but this can be fix by removeing a single line [I have done so in my fork](https://github.com/w-e-w/stable-diffusion-webui-zoomimage/tree/remove-relative-position-of-the-image)

if you're asking about submitting to the index then
currently your extension seems to basically the basically exact same thing as the existing extension but just with a several UI differences
and in general I don't really like to add extensions that do basically the same thing
I would prefer that people help maintain and improve existing extensions 

if you thinks that your version is substantially better then I can consider added to the index
but you have to convince me why it is better and why not improve on existing extension (so that people that are using them can also get the improvements), such as may be your extension having extra functionality

**Comment by w-e-w** [comment]
okay you do know about https://github.com/viyiviyi/stable-diffusion-webui-zoomimage
I missed a tiny link at the bottom of your readme

**Comment by w-e-w** [comment]
you're welcome to submit extensions for review
but don't be like "here is a wall of text, what do you think"

**Comment by w-e-w** [comment]
if you want my opinion about the image fade in animation
I would say make the time shorter if not just don't have any animation at all
I'm sure some people would like it (I like it myself at first)
but it quickly gets old, becomes useless eye candy that waste time
> like this is just my opinion

**Comment by gutris1** [comment]
> if you want my opinion about the image fade in animation I would say make the time shorter if not just don't have any animation at all I'm sure some people would like it (I like it myself at first) but it quickly gets old, becomes useless eye candy that waste time
> 
> > like this is just my opinion

haha,, thanks
it is indeed a copy from viyiviyi zoom image
I make it, so the zoom and dragging is not out of place
it keep centered, or fit to the edge of the screen when the image width is exceeding the lightbox
just like Photos app on windows



> you're welcome to submit extensions for review but don't be like "here is a wall of text, what do you think?"

:D I'll add more words on the readme sometimes.

> did you deliberately hide them I don't know?

yes I did, most button doesnt really work anymore, thats why I hide them


btw, thank you.

**Comment by w-e-w** [comment]
live preview button dose work

**Pull request merged**
