### PR TITLE
Create sd-webui-controlnet-fastload.json

### PR DESCRIPTION
**Pull request by pk5ls20**
## Checklist:

- [x] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [x] The description is written in English.
- [x] The `index.json` and `extension_template.json` have not been modified.
- [x] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by w-e-w** [comment]
how about this
description: "Save and load controlnet parameters"

**Comment by w-e-w** [comment]
typically you you won't have an extra enabled checkbox for a script because script is only run when selected you should make an always on script / extension
I suggest put it inside gradio accordion or an extra tab

**Comment by pk5ls20** [comment]
Thanks for the suggestion, I will remove the enable checkbox for the script.

**Comment by pk5ls20** [comment]
> how about this description: "Save and load controlnet parameters"

Exactly, controlnet means the extension ["sd-webui-controlnet"](https://github.com/Mikubill/sd-webui-controlnet)

**Comment by w-e-w** [comment]
> Thanks for the suggestion, I will remove the enable checkbox for the script.

ahhh that's not what I mean

**Comment by pk5ls20** [comment]
> > Thanks for the suggestion, I will remove the enable checkbox for the script.
> 
> ahhh that's not what I mean
> 
> > controlnet means the extension ["sd-webui-controlnet"](https://github.com/Mikubill/sd-webui-controlnet)
> 
> I don't think that needs clarifying? last I checked there's only one controlnet

Yes, you are right. so "Easily save the parameters in the Mikubill/sd-webui-controlnet plugin." is more appropriate.
Do I need to close this PR and open a new one?

**Comment by w-e-w** [comment]
> Yes, you are right and I think "Easily save the parameters in the Mikubill/sd-webui-controlnet plugin." is more appropriate.

no what I meant is this description "Save and load controlnet parameters" is sufficient
there is no need to clarify what is controlnet because there's only one control net no need to clarify "Mikubill/sd-webui-controlnet" 


> Do I need to close this PR and open a new one to fix the description?

no need to close
you can make additional changes to your brunch and it will be updated to the PR

**Comment by w-e-w** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/blob/33b8c524b1d2e93a2a4387e98a36bf3292bd3638/index.json#L79-L81

**Comment by pk5ls20** [comment]
> > Yes, you are right and I think "Easily save the parameters in the Mikubill/sd-webui-controlnet plugin." is more appropriate.
> 
> no what I meant is this description "Save and load controlnet parameters" is sufficient there is no need to clarify what is controlnet because there's only one control net no need to clarify "Mikubill/sd-webui-controlnet"
> 
> > Do I need to close this PR and open a new one to fix the description?
> 
> no need to close you can make additional changes to your brunch and it will be updated to the PR

Thanks🥰

**Comment by pk5ls20** [comment]
> "Easily save the parameters in the Mikubill/sd-webui-controlnet plugin."

Thank you for your advice🥰

**Comment by pk5ls20** [comment]
> example
> 
> https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/blob/33b8c524b1d2e93a2a4387e98a36bf3292bd3638/index.json#L79-L81
> 
> like here you don't need to specify what controlnet is everyone who see this will understand if they don't, they probably shouldn't download it

Thank you for your advice🥰

**Comment by w-e-w** [comment]
放棄 我用中文了
感覺我跟你講的你都理解成反的
我是說 你
最初的這 "Save parameters in the Controlnet plugin easily" 感覺詭異


你這插建的功能是保能存與加載Controlnet參數
所以一個簡單的 說明
所以我建議 "Save and load controlnet parameters" "保存與加載Controlnet參數"
我感覺這說明感覺就足夠
什麼"easily" "plugin" 這些額外的詞彙不需要

我不知道你是怎麼理解的
Exactly, controlnet means the extension ["sd-webui-controlnet"](https://github.com/Mikubill/sd-webui-controlnet) 

然後我又跟你說明 你不需要說明/強調controlnet是啥 看到的人都懂 如果不懂代表他們根本不該用你這插件

然後我說明後你貌似理解成我在肯定你??????

**Comment by w-e-w** [comment]
2 你這插件的性質不是script
你這插件是詪contronnet配套使用的

script的限制是 一次只能啟用一個 始於臨時性的 增加功能
我是建議你把體插建做成這樣

**Comment by pk5ls20** [comment]
> 放棄 我用中文了 感覺我跟你講的你都理解成反的 我是說你最初的這 "Save parameters in the Controlnet plugin easily" 感覺詭異
> 
> 你這插建的功能是保能存與加載Controlnet參數 所以一個簡單的 說明 所以我建議 "Save and load controlnet parameters" "保存與加載Controlnet參數" 我感覺這說明感覺就足夠 什麼"easily" "plugin" 這些額外的詞彙不需要
> 
> 我不知道你是怎麼理解的 Exactly, controlnet means the extension ["sd-webui-controlnet"](https://github.com/Mikubill/sd-webui-controlnet)
> 
> 然後我又跟你說明 你不需要說明/強調controlnet是啥 看到的人都懂 如果不懂代表他們根本不該用你這插件
> 
> 然後我說明後你貌似理解成我在肯定你??????

是我理解错了😂
就按照https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions/pull/160?notification_referrer_id=NT_kwDOBtVYzbQ3MzAxNTI2MDgyOjExNDY0NTE5Nw#issuecomment-1667263414 改为 `Save and load controlnet parameters` 吧😂

**Comment by pk5ls20** [comment]
> 2 你這插件的性質不是script 你這插件是詪contronnet配套使用的
> 
> script的限制是 一次只能啟用一個 始於臨時性的 增加功能 我是建議你把體插建做成這樣 image 跟其他插件類似 要用時啟用

我最开始想做成这样, 由于功能所限只能作为Script运行...

**Comment by w-e-w** [comment]
https://github.com/pk5ls20/sd-webui-controlnet-fastload/pull/1

**Comment by pk5ls20** [comment]
> [pk5ls20/sd-webui-controlnet-fastload#1](https://github.com/pk5ls20/sd-webui-controlnet-fastload/pull/1)

非常感谢修改!
我刚刚试了一下发现完全可行...

**Comment by w-e-w** [comment]
如果有discordd可以加開發群 遇到問題可以問(有沒有人回答就是另一回事了)
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Contributing

**Pull request merged**
