### PR TITLE
Aspect Ratio Resolutions selector-xhox

### PR DESCRIPTION
**Pull request by xhoxye**
## Checklist:

- [x] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [x] The description is written in English.
- [x] The `index.json` and `extension_template.json` have not been modified.
- [x] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by w-e-w** [comment]
I can see that is a fork of https://github.com/alemelis/sd-webui-ar

as a general rule we don't want to add forks to the index as we want to encourage collaboration
it's preferable if people continue to maintain and improving existing extensions
we also don't want too many similar extensions that does basically the same things
there are some cases where we would add a fork or even switch to the fork on index
such as when an extension is broken
or what a fork is sufficiently different from the original to the point that it has become a different project

I haven't tested the original and your extension myself but from what I can see from issue page it's not broken
and from what I can see your extension is basically the same with just different defaults and slight modifications to original
have you considered contributing to the original project

**Comment by xhoxye** [comment]
OK, I submit PR on original project first, because his last update was 5 months ago, I don't know if he will update and merge this change

**Comment by w-e-w** [comment]
> OK, I submit PR on original project first, because his last update was 5 个月之前, I don't know if he will update and merge this change.

nice, let's give some time for he to respond and see what comes of it
if you didn't respond or decide to reject you were request then we can consider adding yours to index

if at the end we are going to add your essential index then I will have to make the request that you change the

also I remember that we already added another fork of this extension
the last commit of this one is from 3 months ago
consider contributing to this one https://github.com/LEv145/--sd-webui-ar-plus

like I said I don't really want to add too many duplicate extensions, no offense

if you do believe that your changes is for the better
and the use case is sufficiently different I will add your extension

but let's wait for a while

**Comment by w-e-w** [comment]
any updates?

**Comment by xhoxye** [comment]
> any updates?

Nothing happened

**Comment by w-e-w** [comment]
do you still want to add you version to the index
if so I will merge this

**Comment by xhoxye** [comment]
> do you still want to add you version to the index? if so I will merge this

yes

**Pull request merged**
