### PR TITLE
Add sd-webui-prompt-history

### PR DESCRIPTION
**Pull request by namkazt**
Repo: https://github.com/namkazt/sd-webui-prompt-history

Desc: Automatic store your generation info with image and apply back anytime.

Preview:
image

### CODE REVIEW

**Review by w-e-w — COMMENTED** [review]
tag UI related
I pressed the wrong key

**Review by w-e-w — COMMENTED** [review]
UI related
I pressed the wrong key button

**Comment by w-e-w** [comment]
I change the tag to `UI related`

also you probably should add dark mode so that it follows the Gradio theme
the text is currently unreadable in dark mode
image

**Comment by namkazt** [comment]
> I change the tag to `UI related`
> 
> also you probably should add dark mode so that it follows the Gradio theme the text is currently unreadable in dark mode image

thanks, will add dark mode

**Pull request merged**
