### PR TITLE
Stylez

### PR DESCRIPTION
**Pull request by javsezlol1**
## Info 

https://github.com/javsezlol1/Stylez
## Checklist:

- [x] I have read the [`Readme.md`](https://github.com/AUTOMATIC1111/stable-diffusion-webui-extensions)
- [x] The description is written in English.
- [x] The `index.json` and `extension_template.json` have not been modified.
- [x] The `entry` is placed in the `extensions` directory with the `.json` file extension.

### CODE REVIEW

**Comment by w-e-w** [comment]
@javsezlol1 
sorry it took me awhile to have time to reviewring index entries

---

issues that I have found from a quick review

do not assume that the style that CSV is in the default location
https://github.com/javsezlol1/Stylez/blob/main/scripts/Stylez.py#L107

don't assume that your extension is installed under the directory of your repo name
and it ma not be in <webui root>/extensions/<repo name> ar all
https://github.com/javsezlol1/Stylez/blob/main/scripts/Stylez.py#L122

see `--data-dir` `--styles-file`

https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings

also
https://github.com/javsezlol1/Stylez/blob/main/scripts/Stylez.py#L14
```py
# this 
from extensions.Stylez.scripts import promptgen as PG
# should be just
from scripts import promptgen as PG
```
otherwise it will break if the extension is installed under a different directory

this is just a quick review, there might be other issues that I have noticed

**Comment by javsezlol1** [comment]
Okay thanks will work on fixing these. As for the reason I created my own configs. I couldnt workout how to save or load from the the main configs file, I didn't want to just import it as I'm pretty sure that's it is possible to use ahred opt or something along those lines

**Comment by javsezlol1** [comment]
> @javsezlol1
> 
> > Okay thanks will work on fixing these. As for the reason I created my own configs. I couldnt workout how to save or load from the the main configs file, I didn't want to just import it as I'm pretty sure that's it is possible to use ahred opt or something along those lines
> 
> there are lots of examples on how to add settings for extensions and how to access the values https://github.com/Mikubill/sd-webui-controlnet/blob/main/scripts/controlnet.py#L1081 https://github.com/Chaest/sd-webui-sc-loader/blob/master/scripts/main.py#L11 or another method that I prefer https://github.com/w-e-w/sd-webui-nudenet-nsfw-censor/blob/main/scripts/settings.py#L7 https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/extensions-builtin/canvas-zoom-and-pan/scripts/hotkey_config.py https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/extensions-builtin/Lora/scripts/lora_script.py#L35
> 
> to access a value you basically just
> 
> ```python
> shared.opts.the_key_of_your_setting
> ```
> 
> ahhh ... did you delete your message?

yes i did haha sorry, i misunderstood your message i dont really have any settings to put into opt what i was supposed to be talking about wat the atucal web ui config file that saves default values ect. i dont know how to pull values from there without doing a json.load

i have also just finished fixing all the other stuff you mentioned so hopefully there shouldn't be any issues now ? i used scripts.basedir() for the extension folder and cmd_args.parser.parse_args().styles_file to grab the styles file :)
hope this is okay not the best coder but CTRL+F is a big help haha

**Comment by javsezlol1** [comment]
@w-e-w  just following up is it okay to merge now ?

**Comment by w-e-w** [comment]
@javsezlol1 sorry I must have misread your previous message
I thought you haven't fixed the issues but you were going to

anyway I did another test and found another issue
should be fixed by my PR https://github.com/javsezlol1/Stylez/pull/18

**Comment by w-e-w** [comment]
@javsezlol1
nice I didn't find any more issues
I will merge this now

**Comment by javsezlol1** [comment]
@w-e-w thanks sorry for taking my time, I've had a busy weekend.

**Comment by w-e-w** [comment]
> thanks sorry for taking my time, I've had a busy weekend.

totally understand
and thank you for the extension

**Pull request merged**
