### PR TITLE
changing to fork with more up-to-date scripts

### PR DESCRIPTION
**Pull request by gutris1**
[Repo](https://github.com/gutris1/sd-fast-pnginfo)

### CODE REVIEW

**Comment by w-e-w** [comment]
@NoCrypt
- https://github.com/NoCrypt/sd-fast-pnginfo/pull/9

**Comment by CapsAdmin** [comment]
> Hmm, does curl program exist on windows? In install.py it is used. Maybe it's better to use `urllib.request.urlretrieve(url, outPath)` for compatibility

https://curl.se/windows/microsoft.html

Yeah, since around windows 10. Whether or not that means you should use it is something else. I'd say if you're in python already, just use python.

**Comment by gutris1** [comment]
oops I didn't even think about Windows, fixed now
thanks guys

**Comment by gutris1** [comment]
closing this as I've lost interest.

**Comment by gutris1** [comment]
> * left a message at the wrong place so reposting here again [UPDATE NoCrypt/sd-fast-pnginfo#9 (comment)](https://github.com/NoCrypt/sd-fast-pnginfo/pull/9#issuecomment-2103915328)
> 
> just so you know when possible we don't like to change the url of a extension on the index the reason being changing the URL only changes it for new installations and based on NoCrypt account activity he is still active just last week so in this case it's best to be contact the original repository
> 
> NoCrypt just replyed [NoCrypt/sd-fast-pnginfo#9 (comment)](https://github.com/NoCrypt/sd-fast-pnginfo/pull/9#issuecomment-2103921649)

I understand that, that's why Im closing this PR
Thank you.

**Pull request closed without merging**
